### ISSUE TITLE
Fork of the main process take too much time

### ISSUE THREAD

**Issue by FlorentinDUBOIS** [sozu-proxy/sozu#1038]
Hello,

In production, we saw that the main process use serde_json::to_writer to send its configuration to the new worker which internally use a write syscall which use as delimiter the comma character.
This too slow as it perform mostly syscall of 64B to transfer in our use case a state of more than 200MB.

**Comment by Keksoj** [comment]
this will be greatly improved by #1000 , which itself needs #1060 to be completed first.
