### ISSUE TITLE
Question: Webfinger/Redirect

### ISSUE THREAD

**Issue by Rebar-Spoof** [sozu-proxy/sozu#1066]
Hi!
Love the project, I'm finally (novice selfhoster here) getting it to work one by one with my different applications and learning a lot in the process about proxies, reverse proxies, and even nix. I find Sozu much easier to configure than other reverse proxies, but I have a quick question about its capabilities.
I was wondering specifically if it is able to do redirects, like this application for GoToSocial [here](https://docs.gotosocial.org/en/latest/advanced/host-account-domain/).
I haven't been able to find anything in the documentation if it's able to do a redirect like the Caddy, Traefik, or Nginx examples in the GoToSocial docs.

Edit: Adding the Caddyfile from the linked documentation as an example.
`example.com {                                                                    # account-domain
        redir /.well-known/host-meta* https://social.example.com{uri} permanent  # host
        redir /.well-known/webfinger* https://social.example.com{uri} permanent  # host
        redir /.well-known/nodeinfo* https://social.example.com{uri} permanent   # host
}`

Thanks for creating such an awesome project!

**Comment by Wonshtrum** [comment]
Hi, thanks for your enthusiasm! Sozu does not currently support redirections. A similar issue was already opened: #1009. Unfortunately, we do not plan to add such a capability shortly as we focus on other more important features (like http2). But its implementation should be quite straightforward, so we may revisit this idea later.

**Comment by Rebar-Spoof** [comment]
Gotcha! I think I saw that thread actually but the discussion was a little sparse. I saw some conflicting other posts about regex redirects etc. Thanks for the response! Sorry about the duplicate question, I'll close this one :)
