### ISSUE TITLE
[ feature request ] Add Prometheus metrics

### ISSUE THREAD

**Issue by yonas** [sozu-proxy/sozu#1073]
Coming from #412

statsd is outdated. :-1: 

Prometheus is the new defacto standard. Many sozu users will benefit from direct Prometheus stats.

Leave this open for someone to work on / discuss.

**Comment by FlorentinDUBOIS** [comment]
Hello @yonas,

I am glad you are interested in Sōzu and observability around it. 

We provide a statsd metrics exporter as it is a non-blocking way to export metrics and keep performance high.

If you are interested in collecting those metrics using a prometheus collector. 
You should take a look at this project [github.com/CleverCloud/sozu-prometheus-connector](https://github.com/CleverCloud/sozu-prometheus-connector).

That said, I will close this issue as we have a way to export metrics with prometheus format. Besides, the impolite and imperative tone of your discourse is inappropriate here.
