### ISSUE TITLE
failed to start Sōzu: could not bind to listener: Operation not supported (os error 95)

### ISSUE THREAD

**Issue by fakgayhub** [sozu-proxy/sozu#1118]
Using simple python http server for backend
```python3 -m http.server 1031```

Using ```cargo install sozu``` and ```cargo build --release```

Both not work, keep getting ```failed to start Sōzu: could not bind to listener: Operation not supported (os error 95)```

config.toml
```
[[listeners]]
protocol = "http"
address = "127.0.0.1:8080"

[[listeners]]
protocol = "https"
address = "127.0.0.1:8443"
certificate = "./certificate.pem"
key = "./key.pem"

[clusters]

[clusters.TestCluster]
send_proxy = true
protocol = "http"
load_balancing = "ROUND_ROBIN"

# Frontend configuration
frontends = [
    { address = "127.0.0.1:8080", hostname = "localhost" },
    { address = "127.0.0.1:8443", hostname = "localhost", certificate = "./certificate.pem", key = "./key.pem" }
]

# Backend configuration
backends = [
    { address = "127.0.0.1:1031" }
]
```
Im trying ```sudo netstat -tuln | grep 1031``` and got 

```tcp        0      0 0.0.0.0:1031            0.0.0.0:*               LISTEN```

I can access ```localhost:1031``` or ```127.0.0.1:1031``` , so whats wrong with those errror?

Debian 11
rustup 1.27.1
rustc 1.74.0

**Comment by FlorentinDUBOIS** [comment]
Hello, could you provide us the entire output of Sōzu ? To me, I am wondering if paths to certificate and key are valid 🤔

**Comment by fakgayhub** [comment]
its working already
