### ISSUE TITLE
Is it possible to do regex matching for the purpose of access control? 

### ISSUE THREAD

**Issue by nisbet-hubbard** [sozu-proxy/sozu#1131]
Is it currently possible to do regex matching on request headers in sōzu?

**Comment by Wonshtrum** [comment]
Hello. Unfortunately no, currently Sozu does not provide any form of header-based routing. However, it is a feature we want to include in future versions. The system we will put in place is not yet decided and I can't tell you if it will support regex, a more primitive matching (like equal or prefix), or a more flexible one (like wasm scripting).
