### ISSUE TITLE
serde 0.9.0 has a convenient macro to write JSON, use it in tests?

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#119]
https://github.com/serde-rs/json/releases/tag/v0.9.0

**Comment by nicompte** [comment]
I believe it is not possible (yet?) to get the structure type using the `json!` macro, it always gives `serde_json::Value`.

See in [this playground](http://play.integer32.com/?gist=95c519e8c2062f88ab0b1c506034ef9c&version=undefined) and [the docs](https://github.com/serde-rs/json#constructing-json).

**Comment by dtolnay** [comment]
It's easy to make your own.

```rust
#[derive(Serialize, Deserialize)]
struct User {
    name: String,
}

macro_rules! nicompte {
    ($($tt:tt)+) => {
        ::serde::Deserialize::deserialize(json!($($tt)+)).unwrap()
    }
}

fn main() {
    let b: User = nicompte!({"name": "Bobby"});
}
```

**Comment by nicompte** [comment]
Ah very true, thank you @dtolnay :)

**Comment by Geal** [comment]
in the end, it looked a bit more convenient to have json as files stored separately, since I can point people to https://github.com/sozu-proxy/sozu/tree/master/command/assets to check their implementation of config clients
