### ISSUE TITLE
Parsing of HTTP header: address optionnal SP / LWS / folding

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#122]
Currently, the proxy will only match headers of the form: `<key>: <value>` and will reject the backend response if it does not match. I found some implementations out there which send `<key>:<value>`. While the [RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) allows this, it also allows other forms:

> The field value MAY be preceded by any amount of LWS, though a single SP is preferred. Header fields can be extended over multiple lines by preceding each extra line with at least one SP or HT

I see that there are [some ToDo](https://github.com/sozu-proxy/sozu/blob/master/lib/src/parser/http11.rs#L196) for these issues but I felt like it stills needed its own issue.

**Comment by Geal** [comment]
Fixed in 074411
