### ISSUE TITLE
Websocket: connection hangs if Connection header doesn't only contain Upgrade

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#126]
If the `Connection` header has something like `keep-alive, Upgrade` (or anything != `Upgrade`), the proxy doesn't seem to process the request and the request will hang until the user closes it or a timeout happens.

**Comment by BlackYoup** [comment]
So it seems like this is because of the header's parsing. It seems like this is not planned in the data model that a header can have multiple values.

In that case, the header is parsed until the space symbol, which results in `keep-alive,` for the value.

I opened a new issue about that problem, see #128

**Comment by Geal** [comment]
this should be fixed by b6bc144

**Comment by BlackYoup** [comment]
Yes it is ! I can successfully open a Websocket using my browser and receive / send data to it !
