### ISSUE TITLE
Parsing of HTTP headers: a header can have multiple values

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#128]
A header can have multiple values separated by a comma. The last paragraph of https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2 describes this.

This would help fix #126. May be this comes after #92 ?

**Comment by Geal** [comment]
9818419 should fix this

**Comment by BlackYoup** [comment]
It seems to work indeed, I've only tested it with Websockets and the `Connection` header (which, using a browser, has `keep-alive, Upgrade` as its value)

**Comment by Geal** [comment]
ping
can I close this?

**Comment by BlackYoup** [comment]
It works for websocket so I would say yes
