### ISSUE TITLE
merge all the event loops

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#144]
currently, we start a different event loop per protocol (one for HTTP, one for HTTPS, one for TCP), and this results in duplicate workers.

One worker should be able to handle all of the configured protocols. This means having the `Server` struct (in `src/network/proxy.rs`) not generic on the type of protocol, but decide everything at runtime.

This is a good occasion to refactor the TCP proxy with the other ones, since it already requires multiple listening addresses (other protocols listen on only one socket currently). Message dispatching would be done more on the workers than on the master.

The sockets related for each type of proxy should have different ranges in their token identifiers.

What is the performance impact of deciding at runtime what to do with a socket? Can some parts stay generic over the protocol type?

**Comment by Geal** [comment]
Plan:
- `ProxyConfiguration` ( https://github.com/sozu-proxy/sozu/blob/master/lib/src/network/proxy.rs#L151 ) stays nearly the same: transformation methods for front and back tokens will add a base token integer depending on the chosen range
- `Server<ServerConfiguration,Client>` ( https://github.com/sozu-proxy/sozu/blob/master/lib/src/network/proxy.rs#L161 ) splits in two parts:
  - one specific to the type of proxy (HTTP, HTTPS or TCP) with the methods:
    - notify sending the message to a specific server configuration
    - the loop over an event received for one client (the `ready` method). Maybe this could move to `ProxyConfiguration`?
  - a general event loop (containing the `run` method) that separates its token space in 3 (HTTP, HTTPS and TCP):
    - When an event is receive, we look at the token to know which one will receive it
    - when a config message is received, it is sent to the proxy that must handle it
- the `start` methods stay the same for easy usage, maybe? Or we just start one proxy of the required kind
- the master process will by default send every proxy config message to very worker. This might simplify the code a bit

separating the token space in 3 should leave enough token for every kind (it's a usize).

**Comment by Geal** [comment]
since d7b2dbe it's working, but the design is still a bit awkward

**Comment by Geal** [comment]
Should we also merge the code that finds an app id based on the domain and possible URI prefix? If we centralized that code, we could move up connections to backend as well and merge the implementations. The HTTP and TLS proxy would only handle buffers and network.

**Comment by KellerFuchs** [comment]
FWIW, I would expect it to be very low overhead in most cases (due to branch prediction).

**Comment by Geal** [comment]
as of 97b47fd98d63652fdcb491bcf968 all the crates support the new scheme. There are no more tags, every worker handles everything. A few bugs might appear due to the refactoring, so let's wait a bit for more tests before closing that bug.
