### ISSUE TITLE
add commands to sozuctl to create or remove frontends, backends or certificates

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#150]
`sozuctl` currently supports the following commands:
- shutting down
- upgrade
- status
- state save
- state load

There should be new commands to manage frontends (host, URL prefix pointing to app id), backends (app id pointing to IPs and ports of servers) and certificates (and certificate chains and keys).

**Comment by Geal** [comment]
to get started:
- add the new command with https://clap.rs/ in https://github.com/sozu-proxy/sozu/blob/master/ctl/src/main.rs
- implement communication with the proxy by following code like https://github.com/sozu-proxy/sozu/blob/master/ctl/src/command.rs#L48-L79 communication with the command socket is blocking to ease development
- the format for configuration commands is specified here: https://github.com/sozu-proxy/sozu/blob/master/command/README.md

**Comment by bthuillier** [comment]
If I understand correctly the [README](https://github.com/sozu-proxy/sozu/blob/master/command/README.md#worker-configuration-messages) the command already exist, the only work is to add the new commands and sending to the proxy

**Comment by Geal** [comment]
That's right. And there's some code in the command library to split an Apache-style certificate chain file in a list of certificates, if needed

**Comment by bthuillier** [comment]
OK, so you can assign this issue to me, I don't have any ETA but I hope for the end of next week

**Comment by Geal** [comment]
with a9d729e this should be complete, needs testing

**Comment by Geal** [comment]
ok, it was not really done, but now with 7632aa3 it should be alright ;)
