### ISSUE TITLE
Support for Let's encrypt

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#156]
Thanks to sozu's design, it should be relatively easy to support the [ACME protocol](https://tools.ietf.org/html/draft-ietf-acme-acme-06) to automatically issue certificates.

Using the [sozu command library](https://github.com/sozu-proxy/sozu/tree/master/command), make a new application that would:

- ask the CA for a new validation
- start a small webserver to host the verification id
- send a message to sozu to start proxying requests to the domain and the specific URL path of the verification id, to that local webserver
- once the verification is done, the tool receives the certificate
- tell the proxy to stop connecting to the webserver
- stop the webserver
- tell the proxy to start using the new certificate

This new tool could live in a separate repository under the [sozu github organisation](https://github.com/sozu-proxy)

**Comment by onur** [comment]
If anyone wants to implement this, check out my [acme-client](http://docs.rs/acme-client) crate. It can do most of the ACME related job and sozu can serve challenge token.

**Comment by Geal** [comment]
oh, that's great :)

**Comment by RemiDesgrange** [comment]
Maybe also saying that all HTTP need to be redirect to HTTPS ?

**Comment by Geal** [comment]
that's a separate feature, but thanks for the suggestion, I opened #219 for this

**Comment by Geal** [comment]
this is done in https://github.com/sozu-proxy/sozu-acme
There's a difference with what I specified at first, though: it does not give the new certificate to sozu, because it does not know how many fronts correspond to this certificates (they might be linked to different applications, or one application might have multiple fronts with that certificate). So it stores the certificate, and it must be passed to sozu with another mean (like sozuctl).
