### ISSUE TITLE
Workers not stopped if master exits too quickly

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#158]
I encountered a case where I had a problem in my configuration which lead the master process to exit while some workers remained.

Here are some logs: https://gist.github.com/BlackYoup/00563a7ac6f99a2cb5fddb9c35e90b23

We see that the master process exits because it can't find the unix socket folder (because it doesn't exist) and that the 2 workers spawned a few milliseconds after were not stopped.

Also, the worker report that the `Command channel was closed`. Maybe they should stop if it happens ? Or this is normal behavior to not stop them ?

**Comment by Geal** [comment]
Fixed in f47bab7
