### ISSUE TITLE
front request hangs if sozu can't reach the backends

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#167]
Using the configuration in `bin/config.toml` (with the `answer_503` field commented out and pointing to a valid file), the proxy doesn't seem to serve the `503.html` file when it runs out of backends for a given host.

The proxy only stays at `no more available backends for app` and the front connection hangs forever. Full logs: https://gist.github.com/BlackYoup/e0bb6efe2297d2a5b0039d8c673226fd
`Config.toml`: https://gist.github.com/BlackYoup/30bfa92cd9be89ce1ce09b5354a9ece2

For the record, there was nothing listening on port `1026` so there was literally no backend available (connection refused) 

Shouldn't it serve the `503.html` file if it can't reach backends ?

**Comment by Geal** [comment]
Fixed in 8f7d982
