### ISSUE TITLE
SSL: panick at 'invalid index' when under a lot of SSL connections

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#170]
While running some tests, I noticed that maintaining the `ctrl + r` keyboard shortcut (to refresh) made the proxy crash. (for the record, maintaining `ctrl + r` refreshes the web page a lot, and made a lot of connections to the proxy)

It seems like the issue is only when using SSL connection, I couldn't reproduce with plain HTTP. Also, I couldn't reproduce in local using `python -m SingleHTTPServer` even using SSL. The backend is a PHP application and is hosted on the same machine as the proxy.

Sozu is running at the latest master commit.

Logs: https://gist.github.com/BlackYoup/8c87d169df4204e0b8c09cd0349d2c62
The sozu config is quite like the one in the repository.

**Comment by Geal** [comment]
could you test again? Since the source changed a lot, I think the file and line infos from the backtrace does not correspond anymore

**Comment by Geal** [comment]
Fixed in 13d0f00
