### ISSUE TITLE
metrics message

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#172]
There should be a message to gather statistics from the different workers.

Plan:
- add a new message (request and response) in [lib/src/messages.rs](https://github.com/sozu-proxy/sozu/blob/master/lib/src/messages.rs#L133-L157)
- implement the message handling in the proxies: https://github.com/sozu-proxy/sozu/blob/master/lib/src/network/http.rs#L589-L657 https://github.com/sozu-proxy/sozu/blob/master/lib/src/network/tls.rs#L940-L1014 https://github.com/sozu-proxy/sozu/blob/master/lib/src/network/tcp.rs#L467-L529
- the message should return currently available state, like the number of current connections ( [clients.len()](https://github.com/sozu-proxy/sozu/blob/master/lib/src/network/session.rs#L162) ) or the number of apps managed. For information that requires storing data for a longer time, we'll see later.
- maybe handle the message here: https://github.com/sozu-proxy/sozu/blob/master/bin/src/command/orders.rs if it is a "ProxyConfiguration" message, you might not need to do anything there
-implement the command in https://github.com/sozu-proxy/sozu/blob/master/ctl maybe aggregate data from various workers

**Comment by BlackYoup** [comment]
I'll try that one

**Comment by Geal** [comment]
with #213 done we can now close this
