### ISSUE TITLE
optimize has_message_id

### ISSUE THREAD

**Issue by timglabisch** [sozu-proxy/sozu#177]
the current implementation iterates over all connections when sending an answer (O(clients)).

https://github.com/sozu-proxy/sozu/blob/50bfe8e3fdd861637c7caaee7cd500507383837c/bin/src/command/mod.rs#L302

1. i am not sure but one answer can just go to one client? so a `break` is missing here?
2. i stubled over this because i am looking for a way to implement such a scenario (O(1)) . This should be possible when a client would have a id?

**Comment by Geal** [comment]
I'm currently rewriting that part, so the behaviour might change a bit. This should not be performance critical anyway, since there's a limit to the number of concurrent clients we accept (128 IIRC)

**Comment by Geal** [comment]
current code does not do that now AFAIK
