### ISSUE TITLE
Shutdown processus

### ISSUE THREAD

**Issue by zepouet** [sozu-proxy/sozu#183]
Hello,

Maybe I am wrong but i imagine that command

`../target/debug/sozuctl -c config.toml shutdown --hard`

should shutdown and stop the processus ran by 

`../target/debug/sozu start -c config.toml`

But the processus is still alive. Maybe misconceptions of program objectives and parameters.

Thanks

PS : same effects on Linux 17.04 ans MacOSX

**Comment by Geal** [comment]
ok, I found the issue, working on it

**Comment by Geal** [comment]
ok, so it will need a bit more work, but currently I set it up to panic on a `HardStop` message once all workers have stopped :)

**Comment by Geal** [comment]
ok, it should work now
