### ISSUE TITLE
provide default info at compile time for distribution packaging

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#199]
There are things like the location of the configuration file, the command socket or the logs, that could be specified at compile time instead of through a command line argument every time. That kind of information is often specific to the distribution, so it should be modifiable at build time.

Proposal: get an environment variable in a [build script](http://doc.crates.io/build-script.html) that generates some code to specify the path. If the environment variable is not there, fall back on asking the location of the config file from the command line. If a default location was indicated at compile time but there's a command line argument providing another location, use the command line argument instead.

**Comment by nikhotine** [comment]
Hi,
I had done some work on this issue and pushed some changes [here](https://github.com/nikhotine/sozu/commit/a138ad6fcb123c0eb84cacb96b382133d0e26967).

I am kind of new to the Rust ecosystem so needed some feedback on the implementation. I'd be happy to work on this issue and send a pull request. Thanks.

**Comment by Geal** [comment]
now that I read the code, wouldn't that be much easier to just tell distribution packagers to set those environment variables at build instead of fixing their values in a build script? And mark the config file as required or not by clap depending on whether the env variable was there at compile time (see https://doc.rust-lang.org/std/macro.option_env.html it might help)

**Comment by nikhotine** [comment]
Hi, thanks for the suggestions. Using `option_env!` definitely seems cleaner than fixing the values in the build script and using `env!`. Will work on this over the weekend and send a PR.

**Comment by Geal** [comment]
@nikhotine hi! How did it go? could you send a PR?

**Comment by Geal** [comment]
fixed in #229
