### ISSUE TITLE
Issue when displaying 503 page

### ISSUE THREAD

**Issue by k33g** [sozu-proxy/sozu#201]
### Context

my setup is like that:

```
sozu-demo/
├── 404.html
├── 503.html
├── command_folder
│   └── sock
├── demo.toml
├── sozu # this is the clone of sozu repository
│   ├─
```

I built Sozu as explaines in the `README.md` file

The content of `demo.toml`

```
command_socket = "./command_folder/sock"
saved_state    = "./state.json"
log_level      = "info"
log_target     = "stdout"
command_buffer_size = 16384
worker_count = 2
handle_process_affinity = false

[metrics]
address = "192.168.59.103"
port = 8125

[http]
address = "127.0.0.1"
max_connections = 500
port = 9090
buffer_size = 16384
answer_404 = "./404.html"
answer_503 = "./503.html"


[applications]

[applications.MyApp]
hostname   = "localhost"
frontends = [ "HTTP" ] # list of proxy tags
backends  = [ "192.168.1.23:8080" ] # list of IP/port 
```

The source code of my `503.html` page:

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <style>
    .title
    {
      font-family: "Source Sans Pro", "Helvetica Neue", Arial, sans-serif;
      display: block;
      font-weight: 300;
      font-size: 60px;
      color: #35495e;
      letter-spacing: 1px;
    }
    </style>
  </head>
  <body>
    <h1 class="title">
      😢 Ouch...
    </h1>
  </body>
</html>
```

### Running

I started Sozu:

```
./sozu/target/debug/sozu start -c ./demo.toml
```

And ✨ if I open http://localhost:9090 I can see my website (http://192.168.1.23:8080)

### Remove backend

Then I removed the backend:

```
./sozu/target/debug/sozuctl --config ./demo.toml  backend remove --id MyApp --ip 192.168.1.23 --port 8080
```

and then

with Chrome when opening http://localhost:9090 I got nothing:

<img width="348" alt="chrome" src="https://user-images.githubusercontent.com/491848/28723887-897d7744-73b8-11e7-896f-87d6cc4b6cff.png">

with FireFox I got the HTML code but not the rendered HTML

<img width="397" alt="firefox" src="https://user-images.githubusercontent.com/491848/28724089-35aa7c9c-73b9-11e7-9263-9ed2e441f544.png">

with Safari (btw I'm on OSX Sierra):

<img width="572" alt="safari" src="https://user-images.githubusercontent.com/491848/28723857-6c230ff6-73b8-11e7-85ed-b99f6cd7fa79.png">

Any idea? What I have done wrong?

**Comment by Geal** [comment]
The `answer_404` and `answer_503` files must include the HTTP headers for the answer. That should be documented.

**Comment by k33g** [comment]
@Geal you mean something like `<meta http-equiv="Content-type" content="text/html; charset=utf-8" />`

**Comment by Geal** [comment]
no, the HTTP headers. Something like:

```
HTTP/1.1 503 your application is in deployment
Cache-Control: no-cache
Connection: close

<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <style>
    .title
    {
      font-family: "Source Sans Pro", "Helvetica Neue", Arial, sans-serif;
      display: block;
      font-weight: 300;
      font-size: 60px;
      color: #35495e;
      letter-spacing: 1px;
    }
    </style>
  </head>
  <body>
    <h1 class="title">
      😢 Ouch...
    </h1>
  </body>
</html>
```

**Comment by k33g** [comment]
oh 😳 yes it's better, thx

- FireFox ✅
- Safari ✅
- Chrome, I think I have an issue with the cache
