### ISSUE TITLE
Failing to build sozu with cargo : on serde_derive 

### ISSUE THREAD

**Issue by arthurlutz** [sozu-proxy/sozu#207]
Hi, 

sorry, for being a rust newbie. I can't build sozy because of some packaging problem which seems to be on serde_derive

```
~/local/sozu/ctl$ cargo build
warning: `build.rs` files in the same directory as your `Cargo.toml` will soon be treated as build scripts. Add `build = false` to your `Cargo.toml` to prevent this
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading libc v0.2.28
[snip]
   Compiling serde_derive v1.0.10
error[E0523]: found two different crates with name `std` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
  --> /home/arthur/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.10/src/lib.rs:33:1
   |
33 | extern crate proc_macro;
   | ^^^^^^^^^^^^^^^^^^^^^^^^

error: Could not compile `serde_derive`.
Build failed, waiting for other jobs to finish...
error: build failed
$ cargo --version
cargo-0.17.0 (built 2017-03-24)
```

tried to position myself on the 0.1.1 tag, and getting the same error.

**Comment by Keruspe** [comment]
Please update your rust installation and retry

Latest stable version is 1.19 with cargo 0.20

**Comment by arthurlogilab** [comment]
I'm running on ubuntu or debian, is there a recommended way of installing rustc 1.19 and cargo 0.20 ? If I can use debian packages and avoid executing a curl pipe bash, it would be nice.

**Comment by Keruspe** [comment]
Is rustup packaged for those distributions?

**Comment by arthurlogilab** [comment]
It doesn't seem to be the case cf https://www.rust-lang.org/en-US/other-installers.html

**Comment by arthurlogilab** [comment]
installed 1.19 and cargo 0.20, seems to build, you can close this issue (I don't seem to have the rights for that). Thanks for your help.
