### ISSUE TITLE
add more interesting CI scenari

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#21]
In gitlab by @waxzce on Jan 7, 2016, 18:14

based on multiple docker image + nginx

**Comment by Geal** [comment]
In gitlab by @waxzce on Jan 8, 2016, 22:31

mentioned in commit c7d7c94d44eedcf0b8f3a8e9a19be47bbf2c61b8

**Comment by Geal** [comment]
In gitlab by @Geal on Oct 14, 2016, 17:50

Removed ~207 label

**Comment by Geal** [comment]
we should reactivate this, a better CI is necessary as the use cases get more complex

**Comment by Geal** [comment]
investigate using github actions

**Comment by Keksoj** [comment]
linked with #805

**Comment by FlorentinDUBOIS** [comment]
We use the e2e project in the workspace in addition to unit tests. I close this issue as it may live indefinitely
