### ISSUE TITLE
Proxy hang while streaming huge content

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#210]
Here the content is a video content. During the streaming, the client stops receiving data at some point.

Here are the last 5000 lines of sozu logs: https://gist.github.com/BlackYoup/bf034b8f25a2d8a5ff9b4d599a377cac

The content sopped being streamed at `2017-08-03T11:56:54Z`. `2017-08-03T11:57:03Z` is when I stopped the `cURL`

I can't reproduce this bug when I locally download the content, so there may have a latency variable on this bug. The bug takes some minutes to trigger, also, I usually download between 150 and 300M of data before the bug happens.

I can provide more logs and context if needed. I am running commit a85725d9b9d99f4d92e85d6ef95c45b07f4c755c

**Comment by Geal** [comment]
does this still happen with current master?

**Comment by BlackYoup** [comment]
Yes, it still happens using master

**Comment by Geal** [comment]
it would be useful to have a pcap of what happens on the frontend and backedn connections. Maybe the backend stops the connection right after finishing to send?

**Comment by Geal** [comment]
at the line for timestamp 1440547641172612:
```
2017-08-03T11:56:54Z	1440547641172612	29752	DEBUG	TAG-0	sozu_lib::network::protocol::http	820083d2-78ff-451e-8ec6-076bd2ecd0bf	unknown		FRONT [6148914691236517208<-6148914691236517708]: wrote 16384 bytes of 16384, buffer position 268206281 restart position 268206281
```

`buffer position 268206281 restart position 268206281` means it wrote all the data it was supposed to. Was curl expecting more data? Maybe there's a length calculation that(s wrong somewhere. What was the file's size? and the headers?

**Comment by BlackYoup** [comment]
Here are more details:

First of all, I don't think this has anything to do with the network itself. Sockets are still opened and don't get shutdown. I can provide pcaps but it didn't show anything meaningful to me.

I improved logs a bit, so here they are: https://gist.githubusercontent.com/BlackYoup/b4adb7201cac7c5d0ce50ee37e4e448e/raw/b0b75d51dc829cffa69c0a2bb3a37db774703906/gistfile1.txt

There is the last read from back and write to client before the problem happens.

Here is diff I have after expending logs a bit:
```
       //info!("PROXY\t{:?} {:?} | {:?} front: {:?} | back: {:?} ", client_token, events, self.clients[client_token].readiness(), front_interest, back_interest);
+      info!("PROXY\t Got event for client_token: {:#?}", client_token);
+      info!("PROXY\t Got events: {:#?}", events);
+      info!("PROXY\t Client readiness: {:#?}", self.clients[client_token].readiness());
+      info!("PROXY\t Front interest: {:#?}", front_interest);
+      info!("PROXY\t Back interest: {:#?}", back_interest);
```

cURL was expecting more data. Here are the response headers:
```
< HTTP/1.1 200 OK                               
< Transfer-Encoding: chunked                    
< Content-Type: video/x-matroska                
< Accept-Ranges: none                                                                          
< Cache-Control: no-cache                       
< Date: Wed, 23 Aug 2017 22:17:13 GMT         
```

File size is about 4GB and I only download a few hundreds of megabytes, 96MB on this test.

I don't yet understand all the internals but to me, it seems like at some point, the proxy fails to set `Writeable` to the `front_interest` ? We read the data from the backend but we don't send it to the front.

**Comment by BlackYoup** [comment]
I tried to add more logs to the chunk parsing. But it seems like everything's okay here. All parts are `0xffc0` long.

The last chunk logs I have are identical to the previous ones. But after the last `Chunk::parse` call, the backend sends 4 more chunks (maybe it's not always 4, I didn't check) and none of them make it to the `Chunk::parse` method (the one that's called in `parse_response` in the `http11.rs` file)
