### ISSUE TITLE
Docker build is broken on docker hub

### ISSUE THREAD

**Issue by waxzce** [sozu-proxy/sozu#212]
Seems that the docker build is broken on docker hub since the new multistage build  https://hub.docker.com/r/clevercloud/sozu/builds/

It's because docker hub is not up to date: docker/hub-feedback#1039

I can try to make it run on docker cloud, but as it have to be fixed soon, maybe we can just wait for a week or two?

**Comment by Geal** [comment]
ping? Is it fixed now?

**Comment by Geal** [comment]
it works now, yay!
