### ISSUE TITLE
HTTP -> HTTPS redirect

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#219]
this could be an interesting option (activated by default?) for some websites. Also implement HSTS and pub key pinning?

**Comment by allengeorge** [comment]
Any pointers on how to get started with this?

**Comment by Geal** [comment]
here is a rough plan:
- add an option for the HTTPS redirect in the [HttpFront](https://github.com/sozu-proxy/sozu/blob/master/command/src/messages.rs#L134-L155)
- see the [sticky session PR](https://github.com/sozu-proxy/sozu/pull/216) for info on how to transmit that option through config messages
- the option should probably contain the [HSTS options](https://developer.mozilla.org/fr/docs/S%C3%A9curit%C3%A9/HTTP_Strict_Transport_Security)
- if the option is activated, put the HSTS and Location headers in [added_res_headers](https://github.com/sozu-proxy/sozu/blob/3ce0c1220c2c908ce6ce4c98d5b9c1edbc677c0c/src/parser/http11.rs#L718), it will be inserted into the response
- the header should probably be added near usage of the `frontend_from_request` function in `lib/src/network/http.rs`. Maybe look for usage of `ClientStatus::DefaultAnswer`, since the proxy should probably answer with a redirect directly, instead of forwarding to the backend

Don't hesitate to ask in here if you have further questions

**Comment by allengeorge** [comment]
So, a couple of questions:

AFAICT I have to modify [protocol/http](https://github.com/sozu-proxy/sozu/blob/master/lib/src/network/protocol/http.rs#L94) to return the HSTS options in the response header when a client connects.

- Is this correct?
- Why is `added_res_header` a `String` instead of a `Vec<String>`?
- If I have to add additional headers do I need to manually `/r/n` them?
- I assume the caller has to pass in the HSTS options to this constructor. Is there a better way?

**Comment by allengeorge** [comment]
@Geal Sorry to bother you; pinging you again.

**Comment by Geal** [comment]
@allengeorge 
- it's more around here that you would have to add it: https://github.com/sozu-proxy/sozu/blob/master/lib/src/network/protocol/http.rs#L178-L180
- it could be a `Vec<String>` but the parser expects a byte slice, so one vec is easier to manage
- yes, you must pass the `\r\n`
- the options should be passed by the caller, yes, but do not worry about that part for now (since it should come from configuration, so we'll have to modify config messages, etc)

**Comment by BlackYoup** [comment]
@allengeorge Hello! Do you have some work related to this feature or do you need help finishing it? I'm also interested in it :)

**Comment by allengeorge** [comment]
Hi Arnaud - I’m sorry, I got sidetracked. If you could take it on I’m sure it’d be appreciated. TY!

________________________________

**Comment by BlackYoup** [comment]
I opened a Pull request regarding this feature, but there is a small problem.

Say you have an HTTP frontend listening on 8080 and HTTPS frontend on 8443.
With the pull request, the `Location` header would be: `https://localhost:8080`.

A solution could be to get the available fronts for an application and check if one of them is an HTTPS front, and take that port. But it will fail if there are multiple HTTPS fronts.

I don't know how far we want to support the automatic redirection.

**Comment by BlackYoup** [comment]
Do we still have to do something on this issue?

**Comment by Geal** [comment]
up
