### ISSUE TITLE
count requests per second

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#220]
store the global result, but also per HTTP response code, especially 503 errors that indicate the backend is down

**Comment by divarvel** [comment]
I'd be more in favor of using counters, and letting the metrics stack do
the derivation.

**Comment by Geal** [comment]
the proxy will probably need to do the calculation as well, since it must answer the metrics config message

**Comment by Geal** [comment]
with 083ae9f94445309d9a, we now aggregate request counts to display them with `sozuctl metrics`

**Comment by Geal** [comment]
with 61bcc9d the statsd part is done
