### ISSUE TITLE
replace the default circuit breaker for backend servers

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#237]
right now, there's a default circuit breaker with a maximum number of failures of 10. When that number is reached, that server is permanently deactivated (and the number of failures never resets, oops). This gives weird results, like this one: launching the proxy, but forgetting to launch the backend server, the proxy will go through all the backend instances and reach the max number of failures, the user notices the server is not responding, so starts the backend server, but then the proxy does not send traffic to that backend server, since it's marked as unavailable.

Something simple like exponential backoff should be better in that situation.

Here are the relevant parts of the code:
- backend list: https://github.com/sozu-proxy/sozu/blob/cfc3440a0a611f98bd03ab918939f9f25c5557ce/lib/src/network/backends.rs#L94-L136
- the implementation of `Backend`: https://github.com/sozu-proxy/sozu/blob/cfc3440a0a611f98bd03ab918939f9f25c5557ce/lib/src/network/mod.rs#L145-L221

**Comment by mbStavola** [comment]
I have a basic implementation of this in 871a736e767a50493e78174cf1e72bb1d480a21d. I figured you'd want to open the door for different strategies in the future, so I started off with a trait.

Let me know what you think.

**Comment by Geal** [comment]
I added some comments to the commit, but this should really be in a PR. Making a trait is a good thing, as there will probably be other strategies in the future

**Comment by mbStavola** [comment]
Yeah I wasn't sure if it was too soon for a PR since it was a tiny bit of work. I'll fix it up and submit a PR tonight.

**Comment by xpayn** [comment]
Is this issue considered `done` or will it be used as a monitoring issue for different strategies?

**Comment by Geal** [comment]
this is done, but we will return to this in the future, when I add a way to have configurable policies
