### ISSUE TITLE
Sometimes tls requests are not answered with the correct certificate

### ISSUE THREAD

**Issue by Keruspe** [sozu-proxy/sozu#239]
In my case, when some page loads a lot of resources using tls, most of the requests ends up with success, but some of them throw an error about insecure connection as the wrong (the default) certificate is provided.

**Comment by BlackYoup** [comment]
In that case, I commented the `default_app_id` directive and it's working smoothly. So it seems that some requests have been routed to the default application `MyApp` which loads the default certificate too. But why would some requests be redirected to that default application ?

**Comment by Geal** [comment]
cannot reproduce, let's reopen it if we manage to reproduce it
