### ISSUE TITLE
Backend still receive connections after it has been removed

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#262]
I don't know if that's an expected behavior, but to me it should not.

- client A makes a request to app A, backend A will be chosen. Connexion is kept alive
- during the keep alive session, sozu receives the order to remove backend A and add backend B
- client A makes a new request to app A, backend A will be requested if it's still UP, instead of backend B
- client A makes a new request to app A after the keep alive session is closed, backend B will be correctly chosen.

This could lead old clients to be served the wrong backend (mostly an old version of the application they try to reach). Once the backend is shutdown, sozu correctly uses the new backend, as expected

**Comment by BlackYoup** [comment]
The bug also appear if the same backend is added to an other application after it has been removed from its initial application. It redirects to the wrong application until the keep alive session ends.

**Comment by Geal** [comment]
this should be fixed by d712ac1
we now check on both app id and backend address, so it should not even redirect to the wrong application

**Comment by BlackYoup** [comment]
It works :)
