### ISSUE TITLE
do not store metrics data for old applications and instances indefinitely

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#268]
Right now every worker will store its metrics for all the applications that ever received traffic, and all the instances too. Since backend instances can change often for an application, at some point we will have lots of metrics for instances that are long gone.

Should we remove the metrics as soon as we remove the server? Or do we leave enough time for a data collection service to get the final data?

**Comment by BlackYoup** [comment]
+1 for "leave enough time for a data collection service to get the final data".

**Comment by Geal** [comment]
I think for now I'll remove them as soon as the backend is removed and leave some time to think about data collection.
Because there are two ways to get the metrics:
- what will be sent regularly to statsd (or other systems), ie the metrics changes as they happen
- what a data collection system will get by asking on the unix socket (like a dashboard)

There might be two views of the data? Also, how to handle different metrics? Some are an instantaneous value (like, number of concurrent connections), others are more interesting to reset before each collection (like, how many bytes received since last collection)

**Comment by Geal** [comment]
For now done in e8ff973e41097d49

**Comment by Geal** [comment]
done with the metrics rewrite 73aa805 to 3ea91fe
