### ISSUE TITLE
the upgrade process fails for large states

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#272]
perhaps when upgrading, the state should be passed between masters through a file with save_state and load_state

**Comment by Geal** [comment]
with e612cdc the upgrade for the master process is much faster, but forking new workers is still very slow, since the state is passed through the unix socket. The same approach should be used on new workers.

Other problems I have seen:
- instead of replacing the workers, then upgrading the master, we should upgrade the master, then the workers, so that the workers still appear derived from the new master in htop and other tools
- we should replace the workers one by one, since launching a new set of workers right away will consume twice the RAM. So the process would be launch one, wait for it to be ready, soft stop the previous one, wait for the soft stop, do the next worker. All of this can still be done from sozuctl. That means we should always keep enough RAM for one additional worker? Or is there a way to reduce the RAM used by a worker at runtime?
- a new worker should not start listening until it gets the whole state

**Comment by Geal** [comment]
with 3b47de5 the state is now moved through a file when launching a worker. Additionally, it does not start accepting connections before all the routing is configured

**Comment by Geal** [comment]
poke @BlackYoup: how are upgrades working on the test deployment? Going fast enough, etc?

**Comment by BlackYoup** [comment]
I was waiting for the reworks of the upgrade process which just got merged.

Unfortunately, I try to do 5 upgrades at different times this evening and they all hang at the worker upgrade. Here are some logs: https://gist.github.com/BlackYoup/3ea53af617b854db527e0aba150853be

In those logs, you can see I just launched the proxy. I don't have any long lived connections (websocket or other).

Also, it seems it only hang in release mode, not in debug mode. Maybe something's too fast :D

**Comment by Geal** [comment]
@BlackYoup I think it does not hang anymore on state transfer, right?

**Comment by BlackYoup** [comment]
I think this one can be closed now, it's been a few weeks that upgrading with large state has gone pretty well :)
