### ISSUE TITLE
convert sozuctl to structopt

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#278]
currently, sozuctl uses clap, but the list of commands is not well manageable right now: https://github.com/sozu-proxy/sozu/blob/master/ctl/src/main.rs#L21-L219

Moving to structopt could make it easier to handle

**Comment by NotBad4U** [comment]
Due to [#285](https://github.com/sozu-proxy/sozu/pull/285) we can close this issue :smile:

**Comment by Geal** [comment]
yup :)
