### ISSUE TITLE
pretty printing sozuctl's output

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#280]
most commands in sozuctl just display the JSON message that was sent back by sozu. This should be displayed in a nicer way. Some commands already have an output that's displayed with the `prettytable` crate.

Commands to update:

- [X] status
- [X] metrics
- [X] query
- [x] state save
- [x] state load
- [x] state dump
- [x] stop/ stop --hard
- [x] upgrade
- [ ] all the commands using the `order_command` function

**Comment by BlackYoup** [comment]
`state save` and `state load` have a basic output telling what has been done, I'm not sure we need more. `state dump`, well, dumps the proxy configuration. Do we need a friendly output here ? What the difference with state save except that it dumps the state on stdout ?

**Comment by Geal** [comment]
state dump does not need a friendly output. I think it could be merged with state save, in fact.

**Comment by fatimazahramoussaid** [comment]
I think we should use to_string_pretty and not to_string in this function 

fn print_json_response<T: ::serde::Serialize>(input: &T) {
  match serde_json::to_string(&input) {
    Ok(to_print) => println!("{}", to_print),
    Err(e) => {
      eprintln!("Error while parsing response to JSON: {:?}", e);
      exit(1);
    }
  };
}

**Comment by BlackYoup** [comment]
@fatimazahramoussaid If you think the error would have a better output, then do not hesitate to open a pull request for it :) I didn't know about this function and it may indeed be nicer to have the json pretty printed

**Comment by NotBad4U** [comment]
Is there a difference between `println!("{#}", my_json)` and use `to_string_pretty` ?

**Comment by Geal** [comment]
@NotBad4U the first will pretty print rust type (so here, a tree of `serde_json::Value`), the second will make a json file, but with indentation, etc, making it more readable.
It's probably a good idea to do this. @fatimazahramoussaid could you send a pull request for this?

**Comment by NotBad4U** [comment]
@Geal Are you sure that display the type in `Display` ?
