### ISSUE TITLE
add a flag to sozuctl to display the JSON data that was sent back

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#281]
for some commands, the [pretty printing](#280) is nice for humans, but less so for tools that would want to manipulate the results.

For the following commands, add a command like argument `--json` to display the raw result (not the message itself) as json:

- [ ] state dump
- [ ] status
- [ ] metrics
- [ ] query

**Comment by BlackYoup** [comment]
I'm currently working on it, if that's OK.

Just one question: do I directly pass the "display as json or not" boolean to the methods ? Or Do we want to have an enum like `OutputDestination { stdout, json }` ? Maybe later ?

**Comment by NotBad4U** [comment]
I think a pretty way to handle that is to use a Facade Pattern like:
`MyLogger<T: OutputFormat>` where you can `impl` multiple type of your `OutputFormat Trait` like:
JsonOutput, StdoutOutput. That can be more flexible for the futur. And you'll don't have to place a `match` at every function call.

**Comment by BlackYoup** [comment]
@Geal maybe we can close that one now the PR has been merged ? Unless there is some other work to do ?

**Comment by Geal** [comment]
alright then
