### ISSUE TITLE
convert the TCP proxy to use the protocols and upgrade system

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#284]
That way, we could have a first protocol implementing the "proxy protocol", then upgrading to the pipe one, and have only one implementation of this (currently the TCP proxy has its own implementation of piping data back and forth)

**Comment by NotBad4U** [comment]
Hello,
I understand that first thing to do, it's to add [Pipe](https://github.com/sozu-proxy/sozu/blob/master/lib/src/network/protocol/pipe.rs) to the Tcp [Client](https://github.com/sozu-proxy/sozu/blob/05a8b4bd1a3e6363e66e1a40e44e9e6bbea61bc7/lib/src/network/tcp.rs#L47). And that has to work like the Pipe in Http client. 

But what I don't understand is how can we add this, without creating the `upgrade` method itself. 
The `Pipe` is create in the `Http::Client` during a `back_readable` when a `ProtocolResult::Upgrade` is read. But the `back_readable` of `Tcp::Client` doesn't seem to follow the same behavior.
 Thank in advance for your help :smile:

**Comment by Geal** [comment]
for http, it is done in `back_readable` because we might upgrade from HTTP when the server answered a `Connection: Upgrade`. For TCP, no need to implement upgrade, you can create the `Pipe` right from the beginning
