### ISSUE TITLE
Improve the errors management in sozuctl

### ISSUE THREAD

**Issue by NotBad4U** [sozu-proxy/sozu#317]
We use some `expect()`, `unwrap` in `ctl/src/command.rs` we should remove them.

Furthermore, most of the errors are displayed using `println!` and some commands don't exit with a non 0 error code.
* We should exit with a specific code like `1` when a "fatal" error is encountered.
* We should use `eprintln!() to print the error message on `stderr`.

**Comment by Geal** [comment]
is there anything else to do on this?

**Comment by Geal** [comment]
up

**Comment by Geal** [comment]
I changed the println to eprintln and used exit(1) when needed in done in 5959330
@NotBad4U please go through the remaining expect() and unwrap() calls to replace them with more useful messages
