### ISSUE TITLE
ctl: use eprintln!() and exit() on error if needed

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#318]
For now, most of the errors are displayed using `println!()` and some commands don't exit with a non 0 error code.

We should use `eprintln!()` to print on stderr.
We should also exit with a non 0 exit code when a "fatal" error is encountered

**Comment by NotBad4U** [comment]
duplicate of #317

**Comment by BlackYoup** [comment]
#317 has been edited to reflect both issues, closing as duplicate :)
