### ISSUE TITLE
Consider moving ctl code to a reusable library

### ISSUE THREAD

**Issue by kpcyrd** [sozu-proxy/sozu#323]
I discovered this project while browsing dependent crates of [mio-uds](https://crates.io/crates/mio-uds) for example code and the unix domain socket communication between the client and the server is what I've tried to build for a while now in one of my projects (I currently have something ugly in place that I'd rather remove).

I've tried to pull in sozu-communication-lib (I'm not sure if it's meant to be used that way), but there seems to be a significant amount of code that I would have to copy from the server/client to make it work.

My (basic) usecase is along the lines of
```rust
let mut engine = Engine::new();
let channel = Channel::bind("path.sock").unwrap();
loop {
    let msg = channel.recv().unwrap();
    let reply = engine.do_something(&msg.data);
    msg.reply(&reply).unwrap();
}
```
and
```rust
let client = Client::connect("path.sock").unwrap();
let response = client.request(Request::Ping).unwrap();
println!("{:?}", response);
```

I think having the code you wrote in a way that it can be used in other projects (with example code), would be a very good addition to the crates.io ecosystem.

(L)GPL would be ideal, but AGPL would work for me as well.

**Comment by Geal** [comment]
Hello,
could you tell me more about your use case? The code in ctl is a thin wrapper over the command library, and everything needed to talk to sozu should be there.
Note, there's also a futures based wrapper over the command library that you can use.

**Comment by kpcyrd** [comment]
@Geal I think the catch is that I'm not trying to use sozu-command-lib to talk to sozu, but to use it to implement communication between my own client+daemon that is completely unrelated to sozu. :) I think that information might have been missing.

My use-case is a daemon that has a global struct that is shared between all clients. The daemon listens on a unix domain socket for messages, those messages are passed to my struct which modifies itself and returns a response that I send back to the client. A simple example would be a (non atomic) counter that is increased for each request and returns the current number as a response.
