### ISSUE TITLE
Connection reset / fail to parse hostname after the proxy was running for a while

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#325]
So far, the issues happened twice, without much more information. The hostname parsing of the request seems to fail and the proxy outputs `invalid remaining chars after hostname`

The requests were made from both Firefox and cURL, which, I think, can be trusted to create valid HTTP requests.

It happened after the proxy was running for a while (multiple weeks), not on a heavy load.

**Comment by Geal** [comment]
I think this error will not happen again with ad33a38, I don't see why this error would only appear after a while

**Comment by BlackYoup** [comment]
This one couldn't be reproduced in a while, I'm closing it up now and will reopen if I see it again
