### ISSUE TITLE
update slab dependency to 0.4.0

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#343]
there are features that might be useful in that version: https://docs.rs/slab/0.4.0/slab/struct.Slab.html
especially to `shrink_to_fit` method we could use in the soft stop case, to reduce memory pressure.
The implementation is slightly different though: https://docs.rs/slab/0.4.0/slab/index.html#capacity-and-reallocation 
that means if we use slab 0.4.0, it will not put a hard limit on the number of clients

**Comment by NotBad4U** [comment]
Can we tag this `easy` or you think that need to fix a lot breaking changes ?

**Comment by Geal** [comment]
I'm not sure it's that easy, since there are slabs everywhere, and it will have to wait for #340 to be done
