### ISSUE TITLE
Implement the proxy protocol to backend servers

### ISSUE THREAD

**Issue by NotBad4U** [sozu-proxy/sozu#345]
Few words about the proxy protocol: 

> The PROXY protocol provides a convenient way to safely transport connection information such as a client's address across multiple layers of NAT or TCP proxies.

See more [here](https://www.haproxy.com/blog/haproxy/proxy-protocol/).

The idea is to implement at least the proxy protocol for the `tcp` protocol. We should support the version `v1` and `v2` at the end. To begin with, we'll start by implementing the `v1` (ascii version) to evaluate the   feasibility.

TO DO:
- [X] Forward the proxy protocol header from `pipe.rs` to the backend
- [X] Add new feature to the config file for enable the proxy protocol (we have to discuss about this).

**Comment by Geal** [comment]
Fixed in e4fe34c157ac
