### ISSUE TITLE
Respond HTTP 413 Entity Too Large if request line or header is larger than the buffer

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#35]
In gitlab by @Geal on Mar 9, 2016, 22:57

**Comment by Geal** [comment]
In gitlab by @Geal on Mar 9, 2016, 23:08

References for buffer size, etc:
- https://github.com/haywire/haywire/issues/27
- http://stackoverflow.com/questions/686217/maximum-on-http-header-values

There is no cookie size limit (cf http://www.ietf.org/rfc/rfc2965.txt )
Typically, browsers allow 4096 bytes per cookie, 20 cookies per domain, so 81920 bytes, but cookies could be parsed and forwarded separately (cf http://browsercookielimits.squawky.net/ )

**Comment by NotBad4U** [comment]
We can close this one due to the merge of #306.
