### ISSUE TITLE
add a SOZU_BIN environment variable at compile time

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#350]
like `SOZU_CONFIG`, `SOZU_BIN` would fix a path at compile time: the location of the executable

**Comment by FlorentinDUBOIS** [comment]
Hey @Geal, could you give me more insights about this issue. To me Sōzu could do an alternative to which bash command to know where is binary is located. I wonder that this variable could be error prone. What do you think?

**Comment by Geal** [comment]
I am not sure that is needed anymore. I think that predates the code that detects the binary path from the previous executable when upgrading

**Comment by FlorentinDUBOIS** [comment]
Thank you, I close it since it is not needed anymore. A function is used to retrieve the executable path https://github.com/sozu-proxy/sozu/blob/main/bin/src/worker.rs#L192
