### ISSUE TITLE
investigate path issues during upgrade

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#351]
if we replace the executable, the kernel might change the path of the old executable, so during upgrade, sozu will not find the new executable.

Possible solutions:

- store the path of the executable at start up
- get the path of the new executable as optional argument from the upgrade message

**Comment by Geal** [comment]
it should be fixed by f05ca0d

**Comment by BlackYoup** [comment]
Upgrades don't fail because of this anymore. I think we can close the issue.
