### ISSUE TITLE
Metrics: track panics

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#355]
We should have a metric that reports how much panics we've got and when.

I guess `unimplemented!()` or `unreachable!()` are panics too ?

**Comment by Geal** [comment]
in aef54af I added the `worker_restart` metric, shouldn't that be enough? Or do you want to track master panics too?

**Comment by BlackYoup** [comment]
To me, a worker hang means it may have panic, or not. panic is a serious issue while a worker restart is IMHO, less of an issue because the problem has been handled. It would also allow us to exactly track when a worker panic and when it was restarted by the master. Tracking here is "when did the problem happen and when it was solved".  So I'd like to track both.

It would also allow to track master panics, indeed.
