### ISSUE TITLE
configuration file reorganization

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#360]
the TOML configuration file has some awkward bits, maybe it could be improved.
Issues I see right now:

- to activate the HTTP, HTTPS or TCP proxy, the section must appear in the file. Since the TCP proxy has no options (for now), we have to explicitely write `[tcp]` (and nothing afterwards) to activate the TCP proxy
- there are various places where we use a IP/port couple, sometimes there's one option for IP and one for port, other times we use the "<IP>:port" format. . Sometimes we use "address", sometimes we use "ip_address". This should be more consistent
- there are various path used. Are they absolute? Are they relative? relative to what, the config file or sozu's current working directory? Could we show an explicit error right when the config file is parsed instead of when it is used
- as indicated in #358 openssl related configuration options are awkward to use
- for static application configuration, maybe there could be separate sub sections for HTTP, HTTPS and TCP (and return an error when parsing the file if an application has both HTTP and TCP, or both HTTPS and TCP)
- various values are written as a raw number, maybe we could indicate size, like writing "1k", instead of "1000"
- if sozu does not find the configuration file, the error message is not very explicit

**Comment by BlackYoup** [comment]
I guess what's next is kinda part of it, let me know if it's not so I'll open a new issue:

With #459 or even #464, the `config.toml` file structure might change a lot again and, IMHO, would loose its ease of use.

What I had in mind is that, with more and more configuration options coming, either the toml format isn't adapted anymore or we may be able to use the toml format to only describe "basic settings". Basic settings would allow users to test stuff without having to type too much or having to understand a lot of concepts. To me, the current config.toml file (especially around applications) is quite basic and easy to use for new users.

For more advanced usage, we could imagine only having to use the configuration message to set advanced options. The result would be that the `config.toml` file may not support some configuration options to keep it simple.

What do you think?

**Comment by Geal** [comment]
with #358 done, TLS options are a bit cleaner now

**Comment by Geal** [comment]
linked to #348 and #483
