### ISSUE TITLE
implement the proxy protocol for frontend connections

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#361]
[Protocol specification](https://www.haproxy.com/blog/haproxy/proxy-protocol/)

sozu can already write the proxy protocol header (v1) to backend connections in the TCP proxy (#345).

Now we need to handle reception of the proxy protocol header on the frontend connection, for HTTP, HTTPS and TCP, to allow setting up sozu behind TCP proxies.

Plan:

- [ ] implement parsing of the proxy protocol v2 headers
- [ ] add a new protocol to handle reception. Typically, it would only have useful code in its `readable()` method, to recognize the headers then ask for an upgrade
- [ ] add a configuration option **at the proxy configuration level** for HTTP and HTTPS (ie [HttpProxyConfiguration and other structures](https://github.com/sozu-proxy/sozu/blob/master/command/src/messages.rs#L263-L295)), since all applications will share the listener socket. For TCP, it could be done differently for each listener
- [ ] for HTTP, if the option is active, the client starts in proxy protocol then upgrades to HTTP
- [ ] for HTTPS, if the option is active, the client starts in proxy protocol then upgrades to the handshake protocol (do it for openssl and rustls)
- [ ] provide an easy way to test that everything works correctly

**Comment by NotBad4U** [comment]
@Geal 

> add a new protocol to handle reception. Typically, it would only have useful code in its readable() method, to recognize the headers then ask for an upgrade

This new protocol has to handle reception and recognize the header but before to upgrade he should forward the header to the backend.

>  provide an easy way to test that everything works correctly
Can I use [Rouille](https://github.com/tomaka/rouille) to test the HTTP part ?

**Comment by NotBad4U** [comment]
I use this haproxy configuration for #385 
```
frontend proxy_protocol_test
        bind 127.0.0.1:8081 
        mode tcp
        default_backend tcp_node

backend tcp_node
        mode  tcp
        server web1 127.0.0.1:8080 send-proxy-v2
```
