### ISSUE TITLE
sozuctl: check the validity of the configuration file

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#363]
sozuctl should be able to tell if the configuration file is in a valid format or has the valid default options to at least make sozu run.

**Comment by fteychene** [comment]
I'm trying to work on this issue.

Just to be sure, the goal is to handler errors on `sozuctl` and gracefully stop if there is an error on the configuration load and channel creation ?
Does this kind of code is the target (https://github.com/fteychene/sozu/commit/d9b2acfe4ccee663f15d8b69eab8e9dd270d7e7f) or I'm going the wrong way ?
