### ISSUE TITLE
activate logs-debug and logs-trace by default when compiling in debug mode

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#367]

**Comment by BlackYoup** [comment]
Isn't it already the case ? debug and trace logs are always compiled in debug mode (the code checks for the `debug_assertions` feature). Or maybe you want to avoid that check and always enable those two features in debug mode ?
https://github.com/sozu-proxy/sozu/blob/826c1d9af47d8fef31a7c2424398950366a9e68a/lib/src/logging.rs#L473

**Comment by Geal** [comment]
Oh, right, I forgot about that
