### ISSUE TITLE
Add a Protocol for metric and channel

### ISSUE THREAD

**Issue by NotBad4U** [sozu-proxy/sozu#371]
Currently the ListenClient for Channel and metric are insert in the Slab with a `Protocol::HTTPListen`. We should add a new protocol for this case to avoid conflicts. 

`entry.insert(Rc::new(RefCell::new(ListenClient { protocol: Protocol::HTTPListen })));` see [lib/network/tcp.rs](https://github.com/sozu-proxy/sozu/blob/826c1d9af47d8fef31a7c2424398950366a9e68a/lib/src/network/tcp.rs#L948)

**Comment by Geal** [comment]
Fixed in 9e0af88
