### ISSUE TITLE
Add meaningful logs for "investigating single buffer usage: the front->back buffer should not be used while parsing and forwarding the response"

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#374]
When that assert fails, we should have more context as to why it failed

https://github.com/sozu-proxy/sozu/blob/23c25e9e37a0cc5efc0f8c530ec8555e8179ca12/lib/src/network/protocol/http.rs#L569

Maybe for this one too https://github.com/sozu-proxy/sozu/blob/23c25e9e37a0cc5efc0f8c530ec8555e8179ca12/lib/src/network/protocol/http.rs#L425

**Comment by Geal** [comment]
add ref to #83

**Comment by Geal** [comment]
the logs were removed in 41e1cfc
