### ISSUE TITLE
Metrics don't get correctly reported when there are multiple workers

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#381]
The problem lies in the way the workers send their metrics.

Every worker sends its own metrics through statsd with the same serie name. For example, all workers will send the `http.requests` serie with its own values. Each worker will send the values with the same time. 

From here, two things happen:
- With statsd, we don't know which worker sent what
- From what I can see using telegraf, only one worker's metrics are sent to the TimeSeries backend (I don't blame telegraf, I guess that's normal behavior if the points have the same serie name and the same timestamps, but I don't know enough to be sure about this)

We have two choices:
- Each worker could create its own serie and append a custom ID to the serie name like `worker-ID`
- Use a modified version of the statsd protocol that allows us to use tags and the end user would chose which format to use.

As for the modified version of statsd, I don't have much ideas. I quickly searched and I could only find telegraf and datadog using a modified version of the format. But both versions differ.

- telegraf: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/statsd#influx-statsd
- datadog: https://docs.datadoghq.com/developers/dogstatsd/#metrics-1

There might be others I'm not aware of or maybe even a standard, not sure..

**Comment by Geal** [comment]
Here are the results of a (very limited) twitter poll on that subject. I'll look into making the metrics configurable, ie statsd as a basic solution, and statsd with tags as alternative.

Here are ideas of tags we can add (depending on the context):

- worker id
- application id
- request id
- instance id
- proxy type (HTTP, HTTPS or TCP)
- sozu version?

**Comment by BlackYoup** [comment]
Sounds good. I guess we want to use `backend id` instead of `instance id` because of https://github.com/sozu-proxy/sozu/issues/398 :)

**Comment by Geal** [comment]
this can now be activated with the `tagged_metrics` option: https://github.com/sozu-proxy/sozu/blob/master/bin/config.toml#L79

currently we only add worker id, application id and backend id, there might be more interesting metadata we can add later.

**Comment by Geal** [comment]
ping! So, does this work properly now?

**Comment by BlackYoup** [comment]
It seems like it's working as intended after a few tests. I'll try to dig further. I'll reopen if something is not working as intended.
