### ISSUE TITLE
Don't authorize workers to bind multiple times to the same interface:port

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#392]
It's possible to register multiple fronts with the same port. For example, having 3 fronts, 1 HTTP and 2 TCP with 1 different backend each, connections will be processed by any of the frontends.

Messages asking to register a front to an already taken port shouldn't succeed.

**Comment by Geal** [comment]
Fixed in 2a9bb98

**Comment by Geal** [comment]
hmm, it's juste the config part, the configuration messages are not done yet

**Comment by BlackYoup** [comment]
I can't reproduce the original problem, the configuration messages are returned with an error because the workers can't bind to that port. I'm not sure what changed between then and now. I'll let you close this one if you think the current error handling is good or not.

**Comment by BlackYoup** [comment]
Disregard my previous message. I had sozu running in background using systemd, which is why the workers couldn't bind to the ports (because `root` was already listening on them)
