### ISSUE TITLE
Tcp applications: metrics bytes aren't reported when compiled with proxy protocol v2

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#395]
I compiled sozu with #372. I **didn't enable** the proxy protocol. And since then, network metrics aren't taken anymore. I suspect this has something to do with the PR but I can't verify.

Metrics not reported are `bytes_in` and `bytes_out`. They work well for HTTP or HTTPS frontends.

**Comment by Geal** [comment]
should we have different `bytes_in` and `bytes_out` metrics for HTTP, HTTPS and TCP?

**Comment by divarvel** [comment]
that could be in a tag imo. It's the same metric, but in different contexts

**Comment by NotBad4U** [comment]
`bytes_in` and `bytes_out` are metrics use for the Client part and not the communication with the backend. It's a job that need to be done in #385 where we read the header from the Client.

**Comment by NotBad4U** [comment]
I think we can `close` this one since the merge of #372 
Now, we report the metrics:
- `bytes_in`
- `backend_bout`
- `proxy_protocol.errors`

**Comment by Geal** [comment]
we cannot close it yet, there are no metrics in the "send" proxy protocol implementation
