### ISSUE TITLE
Proxy protocol v2: thread 'main' panicked at 'called `Result::unwrap()` on an `Err`

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#396]
I activated proxy protocol on a TCP application with the #372 merge request commits.

`thread 'main' panicked at 'called Result::unwrap() on an Err value: Error { repr: Os { code: 107, message: "Transport endpoint is not connected" } }', src/libcore/result.rs:916:5`

I don't have much more information about that panic but on my setup, it's quite easy to reproduce (it panics every few seconds)

**Comment by Geal** [comment]
fixed in b3ec0bf
