### ISSUE TITLE
Backend or Instance ? Pick one

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#398]
We can see those two words across the code base. While they might mean the same thing, it feels incoherent.

For example:
`sozuctl -c .. backend add --id "app" --instance-id "instance"` => It's the `backend` command but we give an `instance-id` argument.

We also have a `backend` structure in the code base which contains an `instance_id` field:
```
pub struct Backend {
  pub id:                 u32,
  pub instance_id:        String,
  pub address:            SocketAddr,
  pub status:             BackendStatus,
  pub retry_policy:       retry::RetryPolicyWrapper,
  pub active_connections: usize,
  pub failures:           usize,
}
```

And so on.

We need to choose one of those words, not only for the end user's sake but also for contributors / maintainers. Obviously that would mean a total breaking change because it would affect configuration messages like `AddInstance()` or `RemoveInstance()`.

Which word do we want to pick ?
- `Backend`
- `Instance`

To me `Backend` makes more sense, but that's just me.

**Comment by Geal** [comment]
`Backend` will be more consistent, so let's change every use of `instance` to `backend`. I'd rather have a more coherent wording than be stuck with the confusing `ADD_INSTANCE/REMOVE_INSTANCE` messages.

**Comment by Geal** [comment]
should we also rename "front" to "frontend"?

**Comment by NotBad4U** [comment]
I think it's not necessary, frontend is quite explicite. And this term is use by other proxy too

**Comment by BlackYoup** [comment]
Yes, if there is both `front` and `frontend`, we should only keep one word for consistency.

Some (very raw) stats:
```
~ $ rg frontend -i | wc -l         
192
~ $ rg front -i | rg -v end | wc -l
918
```

**Comment by NotBad4U** [comment]
It's okai to be consistent in the documentation and the CLI but IMO it's okai to make shortcut in the code.
