### ISSUE TITLE
support choosing between openssl and rustls at runtime

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#410]
Right now using openssl or rustls is decided by a compilation feature. This does not make it easily testable.
What I'd like:

- keep the configuration option to add openssl, because people might want to build a sozu that does not embed openssl
- if it's built with openssl, a configuration option (in the toml file) chooses which TLS engine to use (should we use the word "engine" when openssl already uses it for something else?)
- if it's not, show an error if the option is set to openssl but we do not have it

Problem: supporting openssl and rustls at the same time would mean choosing at runtime, so do we have two elements here? https://github.com/sozu-proxy/sozu/blob/master/lib/src/network/proxy.rs#L88
But when we build without openssl, we have only the rustls one, so do we need two version of the struct?
Or yet another abstraction layer for openssl and rustls configurations?

**Comment by BlackYoup** [comment]
> should we use the word "engine" when openssl already uses it for something else?

Maybe we could use "backend" or "TLS backend"? It may be confusing. For example, on Exherbo, we use the word "provider" to differentiate alternatives. So maybe "tls provider" ?

**Comment by TBK** [comment]
I would choose "TLS Provider", since "backend" already is used in a different context (https://github.com/sozu-proxy/sozu/commit/f55cc85fdcb16e1175da986cf0f79575d6d73848).

**Comment by Geal** [comment]
provider sounds good :)

**Comment by Geal** [comment]
as done in d14eaef, the option is named use_openssl. I'll change it to "providers" with a string option tomorrow

**Comment by Geal** [comment]
the tls_provider option is added in 2abfc6d
