### ISSUE TITLE
how to handle logs rotation when logging to file?

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#411]
how does logrotate work?
Right now sozu opens the log file when starting, and uses the same file descriptor over the whole life of the process. What happens if the file is moved, deleted, or even truncated while we're still holding a fd?

**Comment by BlackYoup** [comment]
AFAIK, if a file is moved or deleted, it won't really be moved / deleted until there are no more fd pointing to this file.

If it gets trucated, you should still be able to write into it.
