### ISSUE TITLE
Prometheus support

### ISSUE THREAD

**Issue by TBK** [sozu-proxy/sozu#412]
It would be great with built-in support for the Prometheus metrics format so an exporter will not be necessary and Sōzu can join the native club - https://prometheus.io/docs/instrumenting/exporters/#software-exposing-prometheus-metrics :P

**Instrumentation:**
https://prometheus.io/docs/instrumenting/

**Client lib:**
https://github.com/pingcap/rust-prometheus

**Comment by Geal** [comment]
I'm not sure prometheus fits the model of what we want for metrics. Exporters might work better for this, especially considering that the metrics are exposed through the configuration socket on demand

**Comment by Geal** [comment]
closing for now. sozu exports metrics in statsd format, optionally with InfluxDB's tag extension. It's relatively easy to have a local collector (like telegraf, that's in the list) that prometheus can query.
