### ISSUE TITLE
[RFC] Use openssl as the default TLS backend instead of rustls

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#414]
The motivation behinds this change is that to me, rustls doesn't seem ready to be the default option, even if I'd like to see it the default option too.

Best example was that yesterday, I re-compiled the master branch of sozu and wasn't able to reach my backends (timeouts, connections resets, few requests were fine but it's not optimal). I forgot that the `https.tls_provider` config option was added recently and defaulted to rustls. After setting it to `openssl`, everything was working as expected again.

Rustls has a few issues opened and I didn't have time to open more of them yesterday about the problems I had but I'd prefer to see `openssl` as the default TLS backend for now, until rustls gets stabilized a bit and well tested as openssl has been.

Please comment :)

**Comment by Geal** [comment]
done in a76ee6b
