### ISSUE TITLE
New connections get rejected if it fails too much at connecting to backend / can't find a frontend

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#417]
If you try too many requests for an host that doesn't exist or an application that doesn't have any backend available, sozu will reject connections once it goes past the `max_buffers` configuration.

To reproduce, start sozu with no backends available and use `i=0; while true; do i=$((i+1)) && echo "Request $i" && curl lolcatho.st:8080; done`

Curl will show `connection reset by peer` on the 500th request (if you didn't change the `max_buffers` default value) and sozu will log:
```
2018-03-26T20:13:12Z 96925276462859 23718 WRK-00 TRACE  sozu_lib::network::proxy        PROXY   Token(2) got events: Readable
2018-03-26T20:13:12Z 96925281367039 23718 WRK-00 TRACE  sozu_lib::network::proxy        PROXY   Token(2) got events: Readable
2018-03-26T20:13:12Z 96925285808011 23718 WRK-00 TRACE  sozu_lib::network::proxy        PROXY   Token(2) got events: Readable
```
(It's only one line per request but it just logs that)

Also happens when a frontend can't be found:
`i=0; while true; do i=$((i+1)) && echo "Request $i" && curl lolcatho.st:8080 -H "Host: anonexistinghostname"; done`

I'm pretty sure the problem lies where we set 404 or 503 responses to the client when we can't find an application for the given hostname or if we can't connect to a backend. It may also affect 302 (https redirect) responses.

**Comment by Geal** [comment]
this might be fixed by f15dc08, please test

**Comment by BlackYoup** [comment]
Fyi, this doesn't seem to be testable unless #420 is addressed because it will just hang when testing.

**Comment by BlackYoup** [comment]
It's alright now!
