### ISSUE TITLE
TCP: Infinite loop when trying to connect to a backend - retry policy doesn't kick in

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#419]
I get this error from time to time on my test server, at least once a day.

The retry policy seems to not to kick in:
```
Mar 28 21:03:05 exherbo-dedicated sozu[24204]: 2018-03-28T19:03:05Z 7174193995655026 24205 WRK-00 ERROR        error connecting to backend, trying again
Mar 28 21:03:05 exherbo-dedicated sozu[24204]: 2018-03-28T19:03:05Z 7174193995724915 24205 WRK-00 ERROR        error connecting to backend, trying again
Mar 28 21:03:05 exherbo-dedicated sozu[24204]: 2018-03-28T19:03:05Z 7174193995793864 24205 WRK-00 ERROR        error connecting to backend, trying again
Mar 28 21:03:05 exherbo-dedicated sozu[24204]: 2018-03-28T19:03:05Z 7174193995863483 24205 WRK-00 ERROR        error connecting to backend, trying again
Mar 28 21:03:05 exherbo-dedicated sozu[24204]: 2018-03-28T19:03:05Z 7174193995933232 24205 WRK-00 ERROR        error connecting to backend, trying again
```
It could be great to have a better error message which would include the backend it's trying to connect to.

If I trust the metrics, it's looping for 7 hours now. The backend was already down since 41 hours

**Comment by BlackYoup** [comment]
I can't reproduce locally. I only have it on my server. I'll try to gdb it and see what are the paths it takes to end up in this infinite loop

**Comment by Geal** [comment]
I remember putting this comment in the code: https://github.com/sozu-proxy/sozu/blob/master/lib/src/network/http.rs#L341

The puzzling thing is that in the `backend_from_app_id` should return a 503 error there

**Comment by BlackYoup** [comment]
I don't know if that's what I was having but I have this problem using a TCP frontend with a non-responding backend. It's related to #406

**Comment by Geal** [comment]
also linked to https://github.com/sozu-proxy/sozu/pull/452

**Comment by Geal** [comment]
#452 was merged, apparently this works now
