### ISSUE TITLE
Dump buffer content to disk if there was a parsing error

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#44]
In gitlab by @Geal on Apr 8, 2016, 18:37

Add a runtime config option, to activate it dynamically (maybe app specific?)

**Comment by Geal** [comment]
In gitlab by @Geal on Oct 14, 2016, 17:50

Removed ~207 label

**Comment by Geal** [comment]
not sure if that's a good idea in fact

**Comment by BlackYoup** [comment]
Why not ?

**Comment by Geal** [comment]
because it makes it extremely easy to fill up the disk with bogus requests
