### ISSUE TITLE
Metrics: backend.connections reports huge (and incorrect) values

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#447]
![screenshot-2018-4-18 warp10 quantum](https://user-images.githubusercontent.com/6098160/38930358-f4be32f6-430f-11e8-820a-9a235e1ae82a.png)

As you can see on this picture, `backend.connections` increased at some point and never really went down. The unit value on the left is partially hidden, the actual value reported is: `36893488147419103000`.

The setup has two workers. Each worker reports `18446744073709552000` backend connections, which gives the number above if we multiply it by the number of workers.

The value never decreased and is still that high a few hours after.

**Comment by Geal** [comment]
this looks like an integer underflow. My current guess is that it decreased the number of backend connections when it failed to connect to a backend, then decreased it again in the `close` method, so it gets under 0, but the value is unsigned

**Comment by Geal** [comment]
this should be fixed by 94daeaf

**Comment by Geal** [comment]
ping @BlackYoup are metrics still showing huge numbers of backend connections?

**Comment by BlackYoup** [comment]
For the record, the bug is still here

**Comment by Geal** [comment]
Still there on master?

**Comment by BlackYoup** [comment]
At least on tag v0.6.4, probably not since https://github.com/sozu-proxy/sozu/commit/12832ca36291c41d00f6b88626a13c4e5f565c59 but I guess this commit is just a dirty hack until we figure the origin of the problem, isn't it?

**Comment by BlackYoup** [comment]
Here are some underflows:
- Fail at parsing a request https://gist.github.com/BlackYoup/517189634f031975ba5fccbaa1a96478
- No TLS SNI hostname: https://gist.github.com/BlackYoup/5605a5613eaf167aaff88a821a3340d7
- No servername from ssl: https://gist.github.com/BlackYoup/780245a236c60addb4b143ae27c5c6e0
- front parsing error: https://gist.github.com/BlackYoup/69732446600183569fabcc9b4c8701de

**Comment by BlackYoup** [comment]
Fail at parsing a request underflow:
- We never enter the condition to increment the active request: https://github.com/sozu-proxy/sozu/blob/master/lib/src/network/protocol/http.rs#L508...L520
- We then simply decrement when closing the connection: https://github.com/sozu-proxy/sozu/blob/master/lib/src/network/http.rs#L368

**Comment by BlackYoup** [comment]
After a quick look to other errors, I think the root cause is the same, just in different files: we never increment the `active_requests` because the connection / request wasn't OK but when closing the connection, we decrement `active_requests` anyway

**Comment by Geal** [comment]
the underflow on `http.active_requests` should be fixed by 3987d17. Are there others I should look at?

**Comment by BlackYoup** [comment]
Yes, there is still the `backend.connections` underflow but I couldn't see the first time it occurred, yet. Logs before it happens are not meaningful. I'll have a closer look in the next few days

**Comment by Geal** [comment]
the issue with `backend.connections` should be fixed in 9503e4a

**Comment by BlackYoup** [comment]
Didn't see the metrics issue for some time, I'm closing this :)
