### ISSUE TITLE
Metrics: make series prefix configurable instead of hardcoded "sozu"

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#451]
Currently, if you want to run multiple instances of sozu on the same machine / sending its metrics to the same statsd server, the series will all have the same name, prefixed by `sozu`. Or you'd have to spawn multiple statsd servers which would take care of separating series.

I think making it configurable would be a better option, under the `metrics` section of the configuration file.

**Comment by Geal** [comment]
done in bf1b817, please test

**Comment by BlackYoup** [comment]
It works well :)
