### ISSUE TITLE
ciphersuite issue

### ISSUE THREAD

**Issue by shannara** [sozu-proxy/sozu#455]
i create dynamically with sozuctl app with frontend / backend.

```
sozuctl -c config.toml application add --id owncloud-https -h
sozuctl -c config.toml frontend add --hostname owncloud.mydomain --id owncloud-https --certificate certs/owncloud.mydomain.crt
sozuctl -c config.toml backend add --backend-id owncloud-https --id owncloud-https --ip 172.17.1.11 --port 80
```

But when go to website => Error SSL_ERROR_NO_CYPHER_OVERLAP

When inspect, cipher_list only cipher for ECDSE, not AES256-SHA256 in my case, i add them in list but same issue.

but if i create application in config.toml directly it's work.
```
[applications.owncloud-https]

hostname = "owncloud.mydomain"
port = 443
certificate = "./certs/owncloud.mydomain.crt"
certificate_chain = "./certs/owncloud.mydomain.chain"
key = "./certs/owncloud.mydomain.key"

backends = [ "172.17.1.11:80" ]
```

**Comment by Geal** [comment]
ciphersuite selection was fixed recently, this should be working now

**Comment by shannara** [comment]
Hi @Geal,

I test them with new version and working now, great :).
Thanks.
