### ISSUE TITLE
bring back timeout configuration

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#456]
due to some issues with the implementation of timers in mio (which resulted in CPUs busy looping), timeouts were commented out a while ago, then removed.
Right now we (wrongly) rely on TCP timeouts to remove old connections, but we should add back the timers for better behaviour:
- limit the time spent connecting to backends
- close too old frontend connections
- accept new frontend connections directly and put them in a queue, and track their age, to close them if we do not handle them fast enough
- make the frontend timeout configuration configurable at runtime, so we can reduce keepalive connections when under load

We might have to extract code from https://github.com/carllerche/mio-more and maintain it separately

**Comment by NotBad4U** [comment]
Have you take a look at [https://docs.rs/mio-extras/2.0.4/mio_extras/](https://docs.rs/mio-extras/2.0.4/mio_extras/) ?
repo [here](https://github.com/dimbleby/mio-extras)

They recommend to use that in the mio source code:
```rust
#[deprecated(since = "0.6.5", note = "use mio-extras instead")]
#[cfg(feature = "with-deprecated")]
#[doc(hidden)]
pub mod timer;
```

**Comment by Geal** [comment]
yes
