### ISSUE TITLE
Sticky session cookie should be configurable per backend

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#464]
It could be great to have the sticky session cookie value set up through a configuration message (maybe the add backend message?) so it's not sozu's to generate the cookie.

One use case could be that you have multiple reverse proxies (sozu, haproxy,...) running concurrently.  Their configuration managers would generate the same sticky session ID so the routing doesn't break between the different proxies.

**Comment by BlackYoup** [comment]
@Geal Can we now close this one?

**Comment by Geal** [comment]
Yes
