### ISSUE TITLE
make the rustls proxy configurable

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#469]
pass the protocol list to ServerConfig like this: https://docs.rs/rustls/0.12.0/rustls/struct.ServerConfig.html#structfield.versions
for the ciphersuites ( https://docs.rs/rustls/0.12.0/rustls/struct.ServerConfig.html#structfield.ciphersuites ), it's probably not a good idea to reuse the openssl filter syntax since the list of ciphersuites in rustls is small https://docs.rs/rustls/0.12.0/rustls/static.ALL_CIPHERSUITES.html

**Comment by BlackYoup** [comment]
> for the ciphersuites, it's probably not a good idea to reuse the openssl filter syntax since the list of ciphersuites in rustls is small
Do you mean we don't care about filtering and enable them all?

**Comment by Geal** [comment]
TLS version configuration for rustls is done in e45dbd2

**Comment by Geal** [comment]
the rustls ciphersuites are now configurable: 1bbe975
We'll still have to wait for https://github.com/ctz/rustls/issues/186 to be fixed to get a better way to write it, or we'll find a workaround

**Comment by Geal** [comment]
so apparently rustls does not support TLSv1.0 and 1.1 https://github.com/ctz/rustls/issues/33
maybe the configuration parser should show an error for this
