### ISSUE TITLE
Sticky session: cookie SOZUBALANCEID seems to be always looked after, even if the sticky session cookie name has been configured

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#474]
When the `sticky_name` value in the config file has been changed, sozu seems to still look after the `SOZUBALANCEID` cookie in the request's cookies instead of the configured name.

To reproduce:
- configure a different value for `sticky_name` in the config file
- add two backends with different sticky session values
- curl with cookies and use your `sticky_name` value, it should request both backends
- curl with cookies and `SOZUBALANCEID`, it should only request the backend you specified

**Comment by Geal** [comment]
this should be fixed by 9d8258b

**Comment by BlackYoup** [comment]
:+1:
