### ISSUE TITLE
Configuration backends metrics seems to not be correctly reported after backends were added / removed

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#478]
At least the `sozu.configuration.backends` metric doesn't seem to update its number or to wrongly update it.

I've seen this behavior when adding / removing backends through command messages, the reported metric value isn't changing. But it sometimes does.

I didn't reproduce locally yet, I'll try to when I have some time.

**Comment by BlackYoup** [comment]
Reproduced:
- start sozu with one application and two backends, enable the metrics
- the metrics should show 2 backends
- remove one backend and wait a bit for new metrics point to be sent
- metrics still show 2 backends

The problem might not only be for backends, I didn't test applications / frontends

**Comment by BlackYoup** [comment]
Oh, that's because the `self.state.backends` is an `HashMap<AppId, Vec<Backend>>`, we get the length of the `HashMap`, not the total of backends :)

**Comment by Geal** [comment]
fixed in a1baa2a and f025742
