### ISSUE TITLE
ISO 8859-1 in header values

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#479]
we have seen some applications rely on encoding data in ISO 8859-1 charset in header values. This is compliant with [RFC 2616](https://tools.ietf.org/html/rfc2616) but not [RFC 7230](https://tools.ietf.org/html/rfc7230), which obsoletes 2616.
I would tend to stay on 7230 and avoid supporting older versions.

**Comment by BlackYoup** [comment]
Would it be hard to implement both RFC and have them enabled through a compilation flag or something?

**Comment by Geal** [comment]
ISO-8859-1 in header values is allowed with the feature `tolerant-http1-parser` since 834b4ab
