### ISSUE TITLE
optional custom maintenance page per application

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#509]
(different from #508, as the maintenance mode will not be an error)

**Comment by NotBad4U** [comment]
Do we create a new `command::Order` to set an application in "maintenance mode" or we use an already existing one ?

**Comment by NotBad4U** [comment]
I have to add a new flag (e.g. in_maintenance) to the Application struct and maybe we can add other infos like: maintenance_reason, maintenance_started_date. I think this struct may grow in the futur so do I have to create a new struct Application for the protocol (tcp.rs, http.rs, ...) or I continue to use this message::Application struct ?

**Comment by Geal** [comment]
this can be done by routing an application to backends that serve the maintenance page, no need for a custom option
