### ISSUE TITLE
Websocket client don't receive any frames

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#513]
The setup is:

- a client that does websocket connections over TLS
- a basic sozu
- a backend that receives the websocket connections.

The backend successfully receive the websocket frames but the client never receive a response.

The sozu version is 0.7.5 and I don't have much logs for this issue right now. The configuration is very classical with pretty much the default values found in `bin/Config.toml`

**Comment by Geal** [comment]
does this happen on 0.8?

**Comment by BlackYoup** [comment]
It doesn't seem to happen anymore. If it does, I'll reopen :)
