### ISSUE TITLE
Restarted worker doesn't accept connections

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#534]
After the worker crashes, I get a `connection refused` instead of a worker that actually got restarted. The logs say it was but I guess it doesn't go far enough to start listening.

To reproduce:
- start sozu with one worker (easier with 1 worker)
- kill that worker (`kill <pid>`) and wait for it to restart (shouldn't last long)
- try to connect, there should now be a `connection refused` instead of what you expect it to answer

**Comment by Geal** [comment]
fixed in 32eaa5b
