### ISSUE TITLE
Move away from BufferQueue as basic element for everything

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#541]
the `BufferQueue` implementation is very specific to the HTTP 1 proxy, awkward to use in the `Pipe` protocol, and probably unusable for HTTP/2.

I propose the following steps:
- use a pool of `Buffer` instead of `BufferQueue`, and use that pool to initialize a `BufferQueue`
- use `Buffer` directly in protocols like `Pipe`
- move `BufferQueue` specific details out of the HTTP 1 parser
- use the `Buffer` pool in the HTTP/2 parser

side note: should we move to the [bytes crate](https://crates.io/crates/bytes) instead?

**Comment by Keksoj** [comment]
We got entirely rid of `BufferQueue`s!
