### ISSUE TITLE
Add | remove listener with sozuctl

### ISSUE THREAD

**Issue by NotBad4U** [sozu-proxy/sozu#557]
For now, its not possible to `add | remove` a `listener` with `sozuctl`.
 This need to add 2 new messages:
- Add a listener
- Remove a listener
We need to use the `ProxyRequestData::ActivateListener` when we add and `ProxyRequestData::Deactivate` when we remove.

NOTE: this feature can be use in  `sozu-integration-tests` project

**Comment by Geal** [comment]
done in #583
