### ISSUE TITLE
investigate gaea as mio replacement

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#589]
https://docs.rs/gaea

it is a mio fork with a focus on single threaded usage (no readiness events coming from other threads) and no Windows support, so it might be a good fit. The API is very similar so the changes would not be too large

**Comment by Yatekii** [comment]
Gaea is deprecated and they joined forces with mio as per their readme on https://github.com/Thomasdezeeuw/gaea :)

So I guess we can cose this.

**Comment by Geal** [comment]
right, and the 0.12 branch of sozu uses mio 0.7 now: https://github.com/sozu-proxy/sozu/commit/c7ed35cd10a76cc2251a9d53633cad076e4ec1d3
