### ISSUE TITLE
readable TLS socket syscall error: Error { code: ErrorCode(5), cause: None }

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#590]
I was doing a `while true; do curl https://console.clever-cloud.com; done` on a sozu instance and this error popped out in the logs (almost at each request): `readable TLS socket syscall error: Error { code: ErrorCode(5), cause: None }`

The request normally completed with the expected body, curl returning an exit code of 0. I couldn't reproduce using my browser.

**Comment by Geal** [comment]
probably a connection closed without finishing the TLS session. I put the OpenSSL error messages in debug messages in 7582924 so we can ignore them if we want. Maybe I should add a metric for socket errors though? That could have detected the proxy protocol issue
