### ISSUE TITLE
Don't log an error if client closes a keepalive connection after the response has been sent

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#591]
It appears that, after a successful request where the client wanted to do keep-alive, the client closes the connection anyway. Sozu will then log the `front socket error, closing the connection` even though the request has been successfully handled. This log should not be emitted (and metrics shouldn't be sent) for this case because the request was successful.

**Comment by Geal** [comment]
apparently the keep-alive case is already handled. I'm modifying the error message to see which case creates it

**Comment by Geal** [comment]
the new message is in 0b4de4c

**Comment by Geal** [comment]
this should be already fixed in 0.11
