### ISSUE TITLE
Websocket hangs when accessing warp10 through sozu

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#594]
Warp10 has a websocket endpoint: /api/v0/mobius

When trying to connect to this endpoint through sozu, the websocket never connects. I didn't really investigate it yet but it can be reproduced pretty easily.

- Setup a standalone warp10: https://www.warp10.io/content/03_Documentation/02_Installation/01_Standalone
- Change the `standalone.port` in the `etc/conf-standalone.conf` file to `8081`
- Use this sozu app configuration:
```
[applications.warp10-egress]
protocol = "http"
frontends = [
  { address = "0.0.0.0:8080", hostname = "lolcatho.st", path_begin = "/api/v0/mobius" },
]

backends = [
  { address = "127.0.0.1:8081" }
]
```
- Try to connect to the websocket. Using my browser, I go to `lolcatho.st:8080` and then use this javascript code:
```
var ws = new WebSocket('ws://lolcatho.st:8080/api/v0/mobius');
ws.onopen = () => { ws.send('hello!'); };
ws.onclose = () => console.log('socket closed');
ws.onerror = (e) => console.error('error', e);
ws.onmessage = (e) => console.log(e);
```

**Comment by Geal** [comment]
fixed in 353446f
