### ISSUE TITLE
query refactoring

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#595]
Following #588, it appears the query messages should change a bit. In previous versions, everything was organized around proxy types, then listeners. Now we get listeners from their listen address, then the proxy type.

Queries are currently a bit messy because they're supposed to target all proxies and listeners at the same time.

I propose that we add an address field to queries (like most configuration messages), to indicate which listener should give back the information. Results can then be aggregated in the same way as before in sozuctl and other tools.

**Comment by Keksoj** [comment]
Since this issue was written, queries have been heavily refactored, and rewritten in protobuf. The problems pointed out here seem now irrelevant.
