### ISSUE TITLE
cargo install suzo gives error

### ISSUE THREAD

**Issue by karuppiah7890** [sozu-proxy/sozu#598]
https://www.sozu.io/ says `cargo install sozu`. But I get this error asking me to use nightly. May be it could be mentioned in the site that we need to use nightly

```
error: failed to compile `sozu v0.11.0`, intermediate artifacts can be found at `/var/folders/fg/55xcrj215gs2n9gnpz4077y40000gq/T/cargo-install2xqzy2`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/karuppiahn/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.32/Cargo.toml`

Caused by:
  feature `rename-dependency` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["rename-dependency"]` to enable this feature
```

**Comment by Geal** [comment]
which Rust version do you use? This issue is not coming from sozu, but from the backtrace crate, and should have disappeared with recent rust versions

**Comment by karuppiah7890** [comment]
I used this version - `rustc 1.26.0 (a77568041 2018-05-07)`. I just noticed that latest version of rust is 1.36.0 . I just updated it and looks it works. Sorry! My bad!
