### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by huawenyu** [sozu-proxy/sozu#624]
$ cd ~/proj/sozu/bin
$ cargo --version
cargo 1.38.0 (23ef9a4ef 2019-08-20)
$ rustc --version
rustc 1.38.0 (625451e37 2019-09-23)

$ cargo build

warning: trait objects without an explicit `dyn` are deprecated
   --> lib/src/server.rs:132:36
    |
132 |   sessions:        Slab<Rc<RefCell<ProxySessionCast>>,SessionToken>,
    |                                    ^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn ProxySessionCast`

warning: trait objects without an explicit `dyn` are deprecated
   --> lib/src/server.rs:156:39
    |
156 |     let mut sessions: Slab<Rc<RefCell<ProxySessionCast>>,SessionToken> = Slab::with_capacity(10+2*config.max_connections);
    |                                       ^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn ProxySessionCast`

warning: trait objects without an explicit `dyn` are deprecated
   --> lib/src/server.rs:181:31
    |
181 |     sessions: Slab<Rc<RefCell<ProxySessionCast>>,SessionToken>,
    |                               ^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn ProxySessionCast`

warning: trait objects without an explicit `dyn` are deprecated
    --> lib/src/server.rs:1149:27
     |
1149 |       let cl2: Rc<RefCell<ProxySessionCast>> = self.sessions[token].clone();
     |                           ^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn ProxySessionCast`

warning: trait objects without an explicit `dyn` are deprecated
    --> lib/src/server.rs:1548:84
     |
1548 |   pub fn connect_to_backend(&mut self, poll: &mut Poll,  proxy_session: Rc<RefCell<ProxySessionCast>>, back_token: Token)
     |                                                                                    ^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn ProxySessionCast`

warning: unused imports: `CustomAnswers`, `DefaultAnswers`
  --> lib/src/https_rustls/configuration.rs:28:74
   |
28 | use protocol::http::{parser::{RRequestLine,hostname_and_port}, answers::{DefaultAnswers, CustomAnswers, HttpAnswers}};
   |                                                                          ^^^^^^^^^^^^^^  ^^^^^^^^^^^^^

warning: trait objects without an explicit `dyn` are deprecated
   --> lib/src/https_rustls/configuration.rs:720:37
    |
720 |   let mut sessions: Slab<Rc<RefCell<ProxySessionCast>>,SessionToken> = Slab::with_capacity(max_buffers);
    |                                     ^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn ProxySessionCast`

error[E0658]: use of unstable library feature 'inner_deref': newly added
   --> lib/src/protocol/http/mod.rs:163:27
    |
163 |       app_id: self.app_id.as_deref(),
    |                           ^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/50264

error[E0658]: use of unstable library feature 'inner_deref': newly added
   --> lib/src/protocol/http/mod.rs:164:35
    |
164 |       backend_id: self.backend_id.as_deref(),
    |                                   ^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/50264

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `sozu-lib`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by Geal** [comment]
You should try with at least rust 1.40 (as_deref is available since that version)

**Comment by huawenyu** [comment]
Thanks a lot. After update, it's compile succ.

➜  tmp rustc --version 
rustc 1.41.0 (5e1a79984 2020-01-27) 
➜  tmp cargo --version
cargo 1.41.0 (626f0f40e 2019-12-03)
