### ISSUE TITLE
sozuctl metrics does not show old workers during an upgrade

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#631]
we should be able to see the metrics of a worker that is stopping

**Comment by Keksoj** [comment]
We should check this once the 0.14 branch has been merged and put in production.

**Comment by Keksoj** [comment]
I have managed to reproduce the situation and have found that we now get the metrics of a `Stopping` worker during an upgrade.

Indeed, the queries `command_lib::proxy::Query` are passed to all but `Stopped` workers:
