### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by anderson916** [sozu-proxy/sozu#635]
`
   Compiling url v2.1.1
   Compiling hdrhistogram v6.3.4
   Compiling webpki v0.21.2
   Compiling sct v0.6.0
   Compiling rustls v0.16.0
error[E0432]: unresolved imports `libc::sendmmsg`, `libc::mmsghdr`
 --> lib/src/metrics/writer.rs:5:12
  |
5 | use libc::{sendmmsg, mmsghdr, msghdr, iovec, c_void, c_uint};
  |            ^^^^^^^^  ^^^^^^^ no `mmsghdr` in the root
  |            |
  |            no `sendmmsg` in the root
  |
help: a similar name exists in the module
  |
5 | use libc::{sendmsg, mmsghdr, msghdr, iovec, c_void, c_uint};
  |            ^^^^^^^
help: a similar name exists in the module
  |
5 | use libc::{sendmmsg, msghdr, msghdr, iovec, c_void, c_uint};
  |                      ^^^^^^

error[E0425]: cannot find function `sendmmsg` in crate `libc`
   --> lib/src/metrics/writer.rs:106:29
    |
106 |                 let r = libc::sendmmsg(
    |                               ^^^^^^^^ help: a function with a similar name exists: `sendmsg`
    |
   ::: /Users/john/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.66/src/unix/bsd/mod.rs:673:5
    |
673 | /     pub fn sendmsg(
674 | |         fd: ::c_int,
675 | |         msg: *const ::msghdr,
676 | |         flags: ::c_int,
677 | |     ) -> ::ssize_t;
    | |___________________- similarly named function `sendmsg` defined here

warning: unused imports: `LineWriter`, `self`
 --> lib/src/metrics/network_drain.rs:6:15
  |
6 | use std::io::{self,LineWriter,Write,ErrorKind};
  |               ^^^^ ^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: trait objects without an explicit `dyn` are deprecated
  --> lib/src/pool.rs:17:18
   |
17 | pub type Reset = pool_crate::Reset;
   |                  ^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn pool_crate::Reset`
   |
   = note: `#[warn(bare_trait_objects)]` on by default

warning: `...` range patterns are deprecated
  --> lib/src/protocol/http/parser.rs:23:7
   |
23 |     (0...64, 0...64) | (91...96, 91...96) | (123...255, 123...255) => a == b,
   |       ^^^ help: use `..=` for an inclusive range
   |
   = note: `#[warn(ellipsis_inclusive_range_patterns)]` on by default

warning: `...` range patterns are deprecated
  --> lib/src/protocol/http/parser.rs:23:15
   |
23 |     (0...64, 0...64) | (91...96, 91...96) | (123...255, 123...255) => a == b,
   |               ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
  --> lib/src/protocol/http/parser.rs:23:27
   |
23 |     (0...64, 0...64) | (91...96, 91...96) | (123...255, 123...255) => a == b,
   |                           ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
  --> lib/src/protocol/http/parser.rs:23:36
   |
23 |     (0...64, 0...64) | (91...96, 91...96) | (123...255, 123...255) => a == b,
   |                                    ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
  --> lib/src/protocol/http/parser.rs:23:49
   |
23 |     (0...64, 0...64) | (91...96, 91...96) | (123...255, 123...255) => a == b,
   |                                                 ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
  --> lib/src/protocol/http/parser.rs:23:60
   |
23 |     (0...64, 0...64) | (91...96, 91...96) | (123...255, 123...255) => a == b,
   |                                                            ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
  --> lib/src/protocol/http/parser.rs:24:8
   |
24 |     (65...90, 65...90) | (97...122, 97...122) | (65...90, 97...122) | (97...122, 65...90) => *a | 0b00_10_00_00 == *b | 0b00_10_00_00,
   |        ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
  --> lib/src/protocol/http/parser.rs:24:17
   |
24 |     (65...90, 65...90) | (97...122, 97...122) | (65...90, 97...122) | (97...122, 65...90) => *a | 0b00_10_00_00 == *b | 0b00_10_00_00,
   |                 ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
  --> lib/src/protocol/http/parser.rs:24:29
   |
24 |     (65...90, 65...90) | (97...122, 97...122) | (65...90, 97...122) | (97...122, 65...90) => *a | 0b00_10_00_00 == *b | 0b00_10_00_00,
   |                             ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
  --> lib/src/protocol/http/parser.rs:24:39
   |
24 |     (65...90, 65...90) | (97...122, 97...122) | (65...90, 97...122) | (97...122, 65...90) => *a | 0b00_10_00_00 == *b | 0b00_10_00_00,
   |                                       ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
  --> lib/src/protocol/http/parser.rs:24:52
   |
24 |     (65...90, 65...90) | (97...122, 97...122) | (65...90, 97...122) | (97...122, 65...90) => *a | 0b00_10_00_00 == *b | 0b00_10_00_00,
   |                                                    ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
  --> lib/src/protocol/http/parser.rs:24:61
   |
24 |     (65...90, 65...90) | (97...122, 97...122) | (65...90, 97...122) | (97...122, 65...90) => *a | 0b00_10_00_00 == *b | 0b00_10_00_00,
   |                                                             ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
  --> lib/src/protocol/http/parser.rs:24:74
   |
24 |     (65...90, 65...90) | (97...122, 97...122) | (65...90, 97...122) | (97...122, 65...90) => *a | 0b00_10_00_00 == *b | 0b00_10_00_00,
   |                                                                          ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
  --> lib/src/protocol/http/parser.rs:24:84
   |
24 |     (65...90, 65...90) | (97...122, 97...122) | (65...90, 97...122) | (97...122, 65...90) => *a | 0b00_10_00_00 == *b | 0b00_10_00_00,
   |                                                                                    ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
    --> lib/src/protocol/http/mod.rs:1346:10
     |
1346 |       100...199 => { incr!("http.status.1xx"); },
     |          ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
    --> lib/src/protocol/http/mod.rs:1347:10
     |
1347 |       200...299 => { incr!("http.status.2xx"); },
     |          ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
    --> lib/src/protocol/http/mod.rs:1348:10
     |
1348 |       300...399 => { incr!("http.status.3xx"); },
     |          ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
    --> lib/src/protocol/http/mod.rs:1349:10
     |
1349 |       400...499 => { incr!("http.status.4xx"); },
     |          ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
    --> lib/src/protocol/http/mod.rs:1350:10
     |
1350 |       500...599 => { incr!("http.status.5xx"); },
     |          ^^^ help: use `..=` for an inclusive range

warning: unused imports: `CustomAnswers`, `DefaultAnswers`
  --> lib/src/http.rs:29:75
   |
29 | use super::protocol::http::{DefaultAnswerStatus, TimeoutStatus, answers::{DefaultAnswers, CustomAnswers, HttpAnswers}};
   |                                                                           ^^^^^^^^^^^^^^  ^^^^^^^^^^^^^

warning: trait objects without an explicit `dyn` are deprecated
    --> lib/src/http.rs:1297:37
     |
1297 |   let mut sessions: Slab<Rc<RefCell<ProxySessionCast>>,SessionToken> = Slab::with_capacity(max_buffers);
     |                                     ^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn ProxySessionCast`

warning: trait objects without an explicit `dyn` are deprecated
   --> lib/src/backends.rs:138:27
    |
138 |   pub load_balancing: Box<LoadBalancingAlgorithm>,
    |                           ^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn LoadBalancingAlgorithm`

warning: trait objects without an explicit `dyn` are deprecated
    --> lib/src/tcp.rs:1078:37
     |
1078 |   let mut sessions: Slab<Rc<RefCell<ProxySessionCast>>,SessionToken> = Slab::with_capacity(max_buffers);
     |                                     ^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn ProxySessionCast`

warning: unused import: `IntoRawFd`
 --> lib/src/server.rs:8:43
  |
8 | use std::os::unix::io::{AsRawFd,FromRawFd,IntoRawFd};
  |                                           ^^^^^^^^^

warning: trait objects without an explicit `dyn` are deprecated
   --> lib/src/server.rs:132:36
    |
132 |   sessions:        Slab<Rc<RefCell<ProxySessionCast>>,SessionToken>,
    |                                    ^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn ProxySessionCast`

warning: trait objects without an explicit `dyn` are deprecated
   --> lib/src/server.rs:156:39
    |
156 |     let mut sessions: Slab<Rc<RefCell<ProxySessionCast>>,SessionToken> = Slab::with_capacity(10+2*config.max_connections);
    |                                       ^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn ProxySessionCast`

warning: trait objects without an explicit `dyn` are deprecated
   --> lib/src/server.rs:181:31
    |
181 |     sessions: Slab<Rc<RefCell<ProxySessionCast>>,SessionToken>,
    |                               ^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn ProxySessionCast`

warning: trait objects without an explicit `dyn` are deprecated
    --> lib/src/server.rs:1267:27
     |
1267 |       let cl2: Rc<RefCell<ProxySessionCast>> = self.sessions[token].clone();
     |                           ^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn ProxySessionCast`

warning: trait objects without an explicit `dyn` are deprecated
    --> lib/src/server.rs:1681:84
     |
1681 |   pub fn connect_to_backend(&mut self, poll: &mut Poll,  proxy_session: Rc<RefCell<ProxySessionCast>>, back_token: Token)
     |                                                                                    ^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn ProxySessionCast`

warning: unused imports: `CustomAnswers`, `DefaultAnswers`
  --> lib/src/https_rustls/configuration.rs:28:74
   |
28 | use protocol::http::{parser::{RRequestLine,hostname_and_port}, answers::{DefaultAnswers, CustomAnswers, HttpAnswers}};
   |                                                                          ^^^^^^^^^^^^^^  ^^^^^^^^^^^^^

warning: trait objects without an explicit `dyn` are deprecated
   --> lib/src/https_rustls/configuration.rs:740:37
    |
740 |   let mut sessions: Slab<Rc<RefCell<ProxySessionCast>>,SessionToken> = Slab::with_capacity(max_buffers);
    |                                     ^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn ProxySessionCast`

error[E0277]: the trait bound `usize: std::ops::Neg` is not satisfied
   --> lib/src/metrics/writer.rs:115:17
    |
115 |                 -1 => {
    |                 ^^ the trait `std::ops::Neg` is not implemented for `usize`

error: aborting due to 3 previous errors; 33 warnings emitted

Some errors have detailed explanations: E0277, E0425, E0432.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `sozu-lib`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
➜  bin git:(master) rustc --version
rustc 1.44.0 (49cae5576 2020-06-01)
➜  bin git:(master) cargo --version
cargo 1.44.0 (05d080faa 2020-05-06)
`

**Comment by Geal** [comment]
Hello, which platform are you building on?

**Comment by anderson916** [comment]
It is Mac OS 10.15.4.

**Comment by bheesham** [comment]
I'm also experiencing this: 

OS: Mac OS 10.15.5
Rust: rustc 1.44.0 (49cae5576 2020-06-01)

When building the Docker container, I see:

```
error[E0063]: missing fields `__pad1`, `__pad2` in initializer of `libc::msghdr`                                                                                                                                                            
  --> lib/src/metrics/writer.rs:87:26                                                                                                                                                                                                       
   |                                                                                                                                                                                                                                        
87 |                 msg_hdr: msghdr {                                                                                                                                                                                                      
   |                          ^^^^^^ missing `__pad1`, `__pad2`  
```

**Comment by bheesham** [comment]
I can't seem to find `sendmmsg` in the Mac manual pages, so I'm thinking it's not supported on Mac. It seems like there's support for `sendmmsg` on other some other BSDs.

This complicates things a little since the return type of `sendmsg` (`isize`) is different from `sendmmsg` (`i32`), which means the match statement [here](https://github.com/sozu-proxy/sozu/blob/master/lib/src/metrics/writer.rs#L115) will become unhappy (`isize`'s can't be negative).

**Comment by Geal** [comment]
could you test again from this commit: a82514c0 ?
`sendmmsg` is an extended version of `sendmsg` to send multiple messages on a socket at once, so `sendmsg` cannot replace it right away. I updated the code to use the previous system for platforms other than linux (`sendmmsg` is there mainly for performance reasons)

**Comment by anderson916** [comment]
@Geal that commit works. Thanks.

**Comment by bheesham** [comment]
I submitted #637 (adding Mac to the build matrix) which should give a heads up if the build breaks on Mac again.

**Comment by Geal** [comment]
thank you for your help :)
