### ISSUE TITLE
Hardcoded 64-bit number prevents cross-compilation to raspberry 🥧

### ISSUE THREAD

**Issue by leebradley** [sozu-proxy/sozu#639]
I just cross-compiled sozu to raspberry pi, but to do so I had to undo the change made here: https://github.com/sozu-proxy/sozu/commit/a35645336e97343a4be4c846f4fdf326cb216adc

USIZE_MAX is currently set to the max signed 64 bit integer value, `0x8000000000000000`. The pi of course is 32 bit.

I'm not sure what the ramifications my change are, so I'm hesitant to make a PR. Alternatively maybe the const could be based on the usize::MAX somehow?

### Build Details

**Architecture:** `armv7-unknown-linux-gnueabihf`
**Command:** `cross build --target armv7-unknown-linux-gnueabihf` (using https://github.com/rust-embedded/cross)

**Error:**
```
error: literal out of range for usize
  --> src/command/mod.rs:28:27
   |
28 | const HALF_USIZE: usize = 0x8000000000000000usize;
   |                           ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[deny(overflowing_literals)]` on by default
   = note: the literal `0x8000000000000000usize` (decimal `9223372036854775808`) does not fit into the type `usize` and will become `0usize`
```

Other than that small tweak, happy to report that it's working.

**Comment by Geal** [comment]
hello, it should work with 2aa0fbae. I have to rework the event loop in the main process anyway, so that will probably go away soon, but in the meantime it will work on the pi :)

**Comment by leebradley** [comment]
Confirmed it compiles and works on the pi 👍
