### ISSUE TITLE
[sozu-lib] Examples fail on Windows

### ISSUE THREAD

**Issue by Pierstoval** [sozu-proxy/sozu#645]
(sorry for I am a beginner in Rust, therefore might have misunderstood tons of things)

I just cloned the repository and ran `cargo run --example main` and the output makes me think that there's no _real_ support for Windows on this lib:

<details>
<summary>Output log of `cargo run --example main`</summary>
$ cargo run --example main
   Compiling sozu-command-lib v0.11.48 (E:\dev\www\sozu\command)
error[E0432]: unresolved import `mio_uds::UnixDatagram`
  --> command\src\logging.rs:10:5
   |
10 | use mio_uds::UnixDatagram;
   |     ^^^^^^^^^^^^^^^^^^^^^ no `UnixDatagram` in the root

error[E0432]: unresolved import `mio_uds::UnixStream`
 --> command\src\channel.rs:2:5
  |
2 | use mio_uds::UnixStream;
  |     ^^^^^^^^^^^^^^^^^^^ no `UnixStream` in the root

error[E0433]: failed to resolve: could not find `unix` in `os`
 --> command\src\channel.rs:9:14
  |
9 | use std::os::unix::io::{AsRawFd,FromRawFd,IntoRawFd,RawFd};
  |              ^^^^ could not find `unix` in `os`

error[E0432]: unresolved import `std::os::unix`
 --> command\src\channel.rs:8:14
  |
8 | use std::os::unix::net;
  |              ^^^^ could not find `unix` in `os`

error[E0432]: unresolved import `nix::sys`
 --> command\src\scm_socket.rs:1:10
  |
1 | use nix::sys::socket;
  |          ^^^ could not find `sys` in `nix`

error[E0432]: unresolved import `nix::sys`
 --> command\src\scm_socket.rs:2:10
  |
2 | use nix::sys::uio;
  |          ^^^ could not find `sys` in `nix`

error[E0432]: unresolved import `nix::Result`
 --> command\src\scm_socket.rs:3:5
  |
3 | use nix::Result as NixResult;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ no `Result` in the root

error[E0433]: failed to resolve: could not find `unix` in `os`
 --> command\src\scm_socket.rs:8:14
  |
8 | use std::os::unix::io::{RawFd, FromRawFd, IntoRawFd};
  |              ^^^^ could not find `unix` in `os`

error[E0432]: unresolved import `std::os::unix`
 --> command\src\scm_socket.rs:7:14
  |
7 | use std::os::unix::net;
  |              ^^^^ could not find `unix` in `os`

error[E0412]: cannot find type `RawFd` in this scope
  --> command\src\channel.rs:85:23
   |
85 |   pub fn fd(&self) -> RawFd {
   |                       ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
  --> command\src\scm_socket.rs:17:11
   |
17 |   pub fd: RawFd,
   |           ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
  --> command\src\scm_socket.rs:22:18
   |
22 |   pub fn new(fd: RawFd) -> ScmSocket {
   |                  ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
  --> command\src\scm_socket.rs:60:20
   |
21 | impl ScmSocket {
   |     - help: you might be missing a type parameter: `<RawFd>`
...
60 |     let mut v: Vec<RawFd> = Vec::new();
   |                    ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
  --> command\src\scm_socket.rs:73:28
   |
73 |     let mut received_fds: [RawFd; MAX_FDS_OUT] = [0; MAX_FDS_OUT];
   |                            ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
   --> command\src\scm_socket.rs:118:47
    |
118 |   pub fn send_msg(&self, bytes: &[u8], fds: &[RawFd]) -> NixResult<()> {
    |                                               ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
   --> command\src\scm_socket.rs:137:55
    |
137 |   pub fn rcv_msg(&self, buffer: &mut [u8], fds: &mut [RawFd]) -> NixResult<(usize, usize)> {
    |                                                       ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
   --> command\src\scm_socket.rs:138:41
    |
21  | impl ScmSocket {
    |     - help: you might be missing a type parameter: `<RawFd>`
...
138 |     let mut cmsg = socket::CmsgSpace::<[RawFd; MAX_FDS_OUT]>::new();
    |                                         ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
   --> command\src\scm_socket.rs:169:30
    |
168 | pub struct Listeners {
    |                     - help: you might be missing a type parameter: `<RawFd>`
169 |   pub http: Vec<(SocketAddr, RawFd)>,
    |                              ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
   --> command\src\scm_socket.rs:170:30
    |
168 | pub struct Listeners {
    |                     - help: you might be missing a type parameter: `<RawFd>`
169 |   pub http: Vec<(SocketAddr, RawFd)>,
170 |   pub tls:  Vec<(SocketAddr, RawFd)>,
    |                              ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
   --> command\src\scm_socket.rs:171:30
    |
168 | pub struct Listeners {
    |                     - help: you might be missing a type parameter: `<RawFd>`
...
171 |   pub tcp:  Vec<(SocketAddr, RawFd)>,
    |                              ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
   --> command\src\scm_socket.rs:169:30
    |
169 |   pub http: Vec<(SocketAddr, RawFd)>,
    |                              ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
   --> command\src\scm_socket.rs:170:30
    |
170 |   pub tls:  Vec<(SocketAddr, RawFd)>,
    |                              ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
   --> command\src\scm_socket.rs:171:30
    |
171 |   pub tcp:  Vec<(SocketAddr, RawFd)>,
    |                              ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
   --> command\src\scm_socket.rs:182:59
    |
181 | impl Listeners {
    |     - help: you might be missing a type parameter: `<RawFd>`
182 |   pub fn get_http(&mut self, addr: &SocketAddr) -> Option<RawFd> {
    |                                                           ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
   --> command\src\scm_socket.rs:190:60
    |
181 | impl Listeners {
    |     - help: you might be missing a type parameter: `<RawFd>`
...
190 |   pub fn get_https(&mut self, addr: &SocketAddr) -> Option<RawFd> {
    |                                                            ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
   --> command\src\scm_socket.rs:198:58
    |
181 | impl Listeners {
    |     - help: you might be missing a type parameter: `<RawFd>`
...
198 |   pub fn get_tcp(&mut self, addr: &SocketAddr) -> Option<RawFd> {
    |                                                          ^^^^^ not found in this scope

warning: unused imports: `BufWriter`, `LineWriter`
 --> command\src\logging.rs:7:35
  |
7 | use std::io::{stdout,Stdout,Write,LineWriter,BufWriter};
  |                                   ^^^^^^^^^^ ^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: trait objects without an explicit `dyn` are deprecated
   --> command\src\config.rs:359:32
    |
359 |     fn cause(&self) -> Option<&error::Error> {
    |                                ^^^^^^^^^^^^ help: use `dyn`: `dyn error::Error`
    |
    = note: `#[warn(bare_trait_objects)]` on by default

warning: use of deprecated item 'time::PrimitiveDateTime::now': This method returns a value that assumes an offset of UTC.
   --> command\src\logging.rs:685:11
    |
685 |   let t = time::PrimitiveDateTime::now();
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: use of deprecated item 'time::PrimitiveDateTime::unix_epoch': This method assumes an offset of UTC.
   --> command\src\logging.rs:686:36
    |
686 |   (Rfc3339Time { inner: t, }, (t - time::PrimitiveDateTime::unix_epoch()).whole_nanoseconds())
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no function or associated item named `from_raw_fd` found for struct `mio::net::TcpListener` in the current scope
   --> command\src\scm_socket.rs:209:30
    |
209 |         let _ = TcpListener::from_raw_fd(*fd);
    |                              ^^^^^^^^^^^ function or associated item not found in `mio::net::TcpListener`

error[E0599]: no function or associated item named `from_raw_fd` found for struct `mio::net::TcpListener` in the current scope
   --> command\src\scm_socket.rs:215:30
    |
215 |         let _ = TcpListener::from_raw_fd(*fd);
    |                              ^^^^^^^^^^^ function or associated item not found in `mio::net::TcpListener`

error[E0599]: no function or associated item named `from_raw_fd` found for struct `mio::net::TcpListener` in the current scope
   --> command\src\scm_socket.rs:221:30
    |
221 |         let _ = TcpListener::from_raw_fd(*fd);
    |                              ^^^^^^^^^^^ function or associated item not found in `mio::net::TcpListener`

warning: unused import: `Read`
 --> command\src\channel.rs:7:20
  |
7 | use std::io::{self,Read,Write,ErrorKind};
  |                    ^^^^

error: aborting due to 29 previous errors; 5 warnings emitted

Some errors have detailed explanations: E0412, E0432, E0433, E0599.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `sozu-command-lib`.

To learn more, run the command again with --verbose.
</details>

I'm building a tool that must be cross-platform, and the most important feature is to build an HTTP server that will proxy requests to a running PHP server, either using `php-fpm` if available (on unix platforms), `php-cgi` as a fallback for Windows, and a native `php -S ...` server as a final fallback.

I searched for some rust libs for this, sozu seems useful, but it needs Windows support, do you think this is something we can work on? I can help, if needed 🙂

**Comment by Geal** [comment]
it will be hard to do, sozu is highly coupled to Linux. From what I see there are two incompatibilities on Windows:
- unix sockets provided by [mio_uds](https://crates.io/crates/mio_uds). For those there could be an alternative implementation for Windows using named pipes, but they would need to integrate with mio's event loop, I'm not sure how to do that
- socket transfer by SCM_RIGHTS is used to transfer sockets between processes during upgrades, that could be deactivated in your use case

it is doable but would require a lot of changes in sozu. Is there any way your project could run in WSL? I've run sozu on there a few times (even for the first version of WSL) and it worked well

**Comment by Pierstoval** [comment]
> it is doable but would require a lot of changes in sozu. Is there any way your project could run in WSL? I've run sozu on there a few times (even for the first version of WSL) and it worked well

For this part, I'd answer "maybe yes", but I really wish to be able to port the binary to Windows. 

If the incompatibility is too much work for just one single open-source project, maybe I'll try to find another solution to create a "simple" proxy to php-fpm/php-cgi. The original project on which I inspire for mine is built in Go and I have no idea of how it's working since it's closed-source (and my project's goal is to be an open-source alternative to this closed-source binary), so maybe looking at Sozu is wrong, or maybe we should work to make it compatible with Windows.

I could make it work with Linux only, but I really don't want to give up Windows users 😄

**Comment by Pierstoval** [comment]
> unix sockets provided by [mio_uds](https://crates.io/crates/mio_uds). For those there could be an alternative implementation for Windows using named pipes, but they would need to integrate with mio's event loop, I'm not sure how to do that

I just noticed that `mio_uds` is deprecated in favor of `mio` 0.7+, and it seems there is another kind of datagram implementation in it that might be suitable for Windows: https://docs.rs/mio/0.7.0/mio/net/index.html

I'm no expert in networks communication nor how they are implemented, but maybe this could help?

**Comment by Geal** [comment]
the unix socket in mio 0.7 will not work on Windows: https://github.com/tokio-rs/mio/blob/master/src/net/mod.rs#L20

for your use case maybe you need something simpler, Sozu is more geared towards large scale load balancers. Take a look at the tide and surf crate, they should be enough to quickly make a small proxy

**Comment by Pierstoval** [comment]
Indeed unix socket won't work on Windows, and `php-fpm` (which is the fastcgi process manager for php that can listen to a socket instead of just a tcp port) isn't available on windows (lack of socket support). Instead, there's the `php-cgi` alternative that listens to TCP ports, so in the end my use-case must use TCP on windows and not unix sockets.

I will look at tide and surf, thanks for the advice 😄

**Comment by shirshak55** [comment]
@Pierstoval  regarding PHP even microsoft has closed its door for its v8 so i wouldn't recommend running on windows system without wsl2. WSL2 should work fine with sozu. 

Even if u don't want to use wsl2
Regarding  proxy i have used Nginx binaries (5 years ago) directly on windows and it worked properly so why not give it a try? And Nginx also has a good reverse proxy .

**Comment by Pierstoval** [comment]
I understand, my need is just elsewhere 😄

I actually am considering about not supporting native windows, and only WSL

**Comment by Pierstoval** [comment]
Closing as "won't fix" because Windows support isn't guaranteed :)
