### ISSUE TITLE
Make jemalloc dependency optional

### ISSUE THREAD

**Issue by LLFourn** [sozu-proxy/sozu#648]
I tried to build sozu on FreeBSD but it failed because jemalloc crate isn't supported in FreeBSD.
This is somewhat ironic because the standard system allocator is jemalloc in FreeBSD.
So it would be nice if jemalloc dependency would be optional.

**Comment by Geal** [comment]
it's done in f43c87dd
is there anything else needed to run it on FreeBSD?

**Comment by LLFourn** [comment]
@Geal Thanks for this. It compiles on FreeBSD now :tada:

**Comment by Geal** [comment]
nice :smile:
