### ISSUE TITLE
check that ulimit settings actually permit the configured max number of connections

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#66]
In gitlab by @Geal on Oct 9, 2016, 11:25

**Comment by Geal** [comment]
check the content of `/proc/<PID>/limits`?

**Comment by BlackYoup** [comment]
I can try to do that if that's ok. Also, what about somaxconn in `/proc/sys/net/core/somaxconn` ?

I would check the limits right after the process's fork and exit with an error message if it doesn't fit the limits. Or do we only print a warning message and lower the max number of connections to the limit we have ?
