### ISSUE TITLE
Backend parse error on early Host header

### ISSUE THREAD

**Issue by moschroe** [sozu-proxy/sozu#662]
When using tag 0.11.52 for a local development setup, I encountered empty responses client-side.

Compiling with trace logging (and adding a number of trace statements), I found the culprit to be [`lib/src/protocol/http/parser.rs:1502`](https://github.com/sozu-proxy/sozu/blob/ef8d13bb69190060173208d154b4c07b045d14cf/lib/src/protocol/http/parser.rs#L1502).

The server, in this case the internal development server of PHP (https://www.php.net/manual/en/features.commandline.webserver.php), sent the following response:

```http
HTTP/1.1 404 Not Found\r\n
Host: local.projectdomain.com\r\n
Date: Wed, 20 Jan 2021 14:12:20 GMT\r\n
Connection: close\r\n
Content-Type: text/html; charset=UTF-8\r\n
Content-Length: 533\r\n
\r\n
<533 byte of content>
```

After patching the code to simply return the state in case of a `Host` header (like in l. 1507) without turning it into an error, the proxy seems to work fine.

Was there a special reason behind explicitly failing the request on headers occurring out of the expected order?

**Comment by Geal** [comment]
Hello,

The issue is not in the order: the `Host` header is used for requests, not responses. Cf https://tools.ietf.org/html/rfc7230#section-5.4

**Comment by moschroe** [comment]
A bit embarassing, to be honest :) I was so focused on finding a bug in sozu because it was the part I introduced to the setup last that I completely overlooked the unusual behaviour of the server.

As it is very odd and only meant for development setups anyway, I'll make do with the ad-hoc patch and the release can stay compliant.

**Comment by Geal** [comment]
it's ok :)
I could have let the Host header go through in responses, it did not do harm, but I've found that being slightly strict about some parts of the RFC help dig up weird bugs
