### ISSUE TITLE
Filename attribute of Content-Disposition header can contain non ASCII characters

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#664]
It seems that this attribute can use a different set of character encoding than the rest of the headers and browsers are okay with it.

I found those two RFC:
- https://tools.ietf.org/html/rfc6266#section-4.3
- https://tools.ietf.org/html/rfc5987

Currently Sozu will fail to parse the backend's response and will close the connection

**Comment by Geal** [comment]
should be fixed by https://github.com/sozu-proxy/sozu/commit/71de74d657f2767eca45ef7e32d0675a9cc77c2c
