### ISSUE TITLE
Introduce rustfmt?

### ISSUE THREAD

**Issue by moschroe** [sozu-proxy/sozu#667]
As the SW is mainly developed for in-house use, I'd understand if you wanted me to leave the arrangement of your sitting room alone.

However, as a possible contributor, I'd appreciate being able to use `rustfmt` and not having to hand-indent code to conform to the existing style. Otherwise it would lead to lots of whitespace noise.

**Comment by Geal** [comment]
I've been considering it for some time, but it's not going to happen soon. In the meantime, it's possible to setup your editor per project and avoid bringing it in projects not configured for your formatting

**Comment by Geal** [comment]
this will probably be done for the 0.14 release

**Comment by Keksoj** [comment]
Some remarks regarding this **very** necessary `rustfmt` initiative.

Best thing to do, in my opinion, is to have a `rustfmt.toml` in the project, as we may not want to keep the defaults for:

- indentation. 4 spaces helps distinguish levels of functions but may take too much lateral space when natural indentation occurs.
- max line length. 100 characters may disrupt Sōzu's style a bit too much. We could opt for 120, so as to allow wider indentation for instance

On top of that, we may not want to split entire lists of arguments into as many lines.

Example:

```rust
fn a_function(argument_one, argument_two, another_argument,
    plenty_of_arguments, that_take_up_entire_lines, many_lines_over,
    making_any_use_of_rustfmt, change_the_landscape_drastically) -> Result<()> {
   // ...
}
```

```rust
fn a_function(
    argument_one, 
    argument_two, 
    another_argument,
    plenty_of_arguments, 
    that_take_up_entire_lines, 
    many_lines_over,
    making_any_use_of_rustfmt, 
    change_the_landscape_drastically) 
    -> Result<()> {
   // ...
}
```

Or do we ?

BTW: there are *two* impls of `CommandServer` in `bin/src/command/mod.rs`.

**Comment by moschroe** [comment]
In my view, after three or four function arguments, the vertical arrangement becomes much more understandable at a glance. There is a consistent indentation at which all arguments occur and the next visual seperator cue `:␣` will demarcate the type. I'll probably be scrolling a decent amount in any case, so clarity, please.

Max line len would fine by me, as I use a rather narrow font anyway (Iosevka SS09). As a general rule, I would only deviate from the "standard" where absolutely necessary. Any deviation will just open up discussions on a - in the end - rather subjective preference instead of being able to "hide" behind The Standard™. :)

**Comment by Keksoj** [comment]
I happen to agree very much with all your points.

**Comment by Geal** [comment]
done in 8dc92f2548cdc26c

**Comment by moschroe** [comment]
Sorry for necro-posting but... I wanted to tackle TLS client auth once more and noticed that at tag 0.13.6, `cargo fmt` will mix up everything.

Since the linked commit above seems to have fallen victim to some git history mangling, I wonder if this change has been undone in the meantime?

**Comment by Keruspe** [comment]
Current development happen on the 0.14 branch which has rustfmt applied
