### ISSUE TITLE
Suggestion: Add a usage tutorial

### ISSUE THREAD

**Issue by sbrl** [sozu-proxy/sozu#671]
To help new users understand the workflow of how Sozu works, I suggest writing a tutorial showing the basic usage using the recommended workflow. This will help users get up and running with Sozu quicker.

For example, my initial impression was "I need to write a config file? Ok. How do I do that? Hrm, it isn't documented....", followed by "Ok, so I need to use `sozuctl` - how can I use it to setup the basics? This is confusing."

**Comment by Geal** [comment]
could you check the documentation that @gaelreyrol just added?

**Comment by sbrl** [comment]
Wow, awesome! Just what I was looking for. Thanks so much!
