### ISSUE TITLE
When PID file path is defined, but directory not exists server hangs 

### ISSUE THREAD

**Issue by alkavan** [sozu-proxy/sozu#681]
Added PID file configuration: `pid_file_path = "/run/sozu/sozu.pid"` (for systemd).
And if the path `/run/sozu` does not exists, after starting the server, it just hangs, without producing any output, error, or ending the process.

This is somewhat unexpected behavior since in the case of `command_socket = "/run/sozu/sock"` the `/run/sozu` gets automatically created, and I expect it to do the same in the case of PID file.

Or at least throw out some error about the issue and exit the process. Instead it just hangs.

Example of error:
```
thread 'main' panicked at 'could not get command socket folder path: No such file or directory (os error 2)', command/src/config.rs:1076:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Sozu Version: `0.13.3`
System: `RHEL 8`

***

Another issue that might be directly related, for some reason, when I start the service using the provided systemd unit file, the entire run directory (`/run/sozu/`) gets deleted upon startup. I was not able to produce the same behavior out of the systemd context. The service failed to start, and I suspect that the two issues might be related, since the directory gets deleted and does not exists, the PID file is not created and the service hangs not able to start.

**Comment by Geal** [comment]
@Keksoj could you take a look?

**Comment by Keksoj** [comment]
Sure!

**Comment by Keksoj** [comment]
As far as I digged, this error trickles up very well:

```
Couldn't write the PID file to /wrong/path. Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
But the `error!` macro doesn't work. If we comment out the call to the macro, `std::process::exit(1);` is executed all right.

Will dig in the macro.

**Comment by Keksoj** [comment]
Turns out in `main.rs` the logger wasn't initialized before trying to write the PID file, which is why it hanged.

Fix is on the way.
