### ISSUE TITLE
"lifetime of a session" documentation

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#689]
I will write a document indicating what happens to a client session, from the moment the socket is accepted to when it is closed, with all of the steps around protocols, requests and responses, keep-alive, etc. I have presented it orally, it helps in understanding sozu's design

**Comment by moschroe** [comment]
If you consider creating sequence diagrams, which could be very helpful to visualise the interactions between the many moving parts (also for configuration), might I suggest [plantuml](https://plantuml.com/sequence-diagram)? Plain text format with nice git diffs and allowing for many output formats.

**Comment by Keksoj** [comment]
Hi @Geal , did you start working on it maybe, or should we start from your oral presentation?

**Comment by Geal** [comment]
You can restart grom the presentation, I have not advanced on it
