### ISSUE TITLE
UPGRADE_MAIN in docker not working (new tag needed)

### ISSUE THREAD

**Issue by F0Xde** [sozu-proxy/sozu#710]
Running `sozuctl upgrade` with `sozuctl` version 0.13.0 (latest on crates.io) and a docker container with `clevercloud/sozu:latest` results in this error message:
```
could not parse message (error=Error("unrecognized command", line: 1, column: 62)), ignoring:
{"id":"UPGRADE-MAIN-QfzMAc","version":0,"type":"UPGRADE_MAIN"}
```
`sozuctl` then waits indefinitely for an answer.

Is the version published with the current docker image possibly too outdated and expects different commands? I assume this happens because the command was previously called `UPGRADE_MASTER`.

**Comment by Keksoj** [comment]
it seems the problem is mostly about the docker CI.
