### ISSUE TITLE
config value for `request_timeout` ignored

### ISSUE THREAD

**Issue by moschroe** [sozu-proxy/sozu#741]
Currently experiencing instances of `408 Request Timeout` running sozu 0.13.6 after 10s when the client starts the request but does not manage to process data fast enough (uploading MiB-range files).

There is a `request_timeout` mentioned in `bin/config.toml` and the config validates but the value seems not to be propagated. As a stop-gap solution I compiled the binary myself, changing the Default impl for `HttpsListener`.

**Comment by FlorentinDUBOIS** [comment]
Hey :wave:,

It may be a duplicated or an unimplemented setting. @Wonshtrum and @Keksoj could you take a look at it?

**Comment by Keksoj** [comment]
If this is solved by #820 we should close it.

**Comment by Keksoj** [comment]
This is effectively solved by #820 as far as I've looked into it ! Congrats @FlorentinDUBOIS !
