### ISSUE TITLE
Build failed on 1.13.0 – cannot find macro in this scope

### ISSUE THREAD

**Issue by av-elier** [sozu-proxy/sozu#745]
Hello. On macos `cargo install` with default version fails to build sozu. Typical error is ``cannot find macro `tag` in this scope``

Happens on stable and beta toolchain, but I see that CI on all three are green. Must be macos thing.

Installs fine with `--version 0.12.0`. On 0.13.0 and 0.13.1 same errors.

Here is full build log: [cargo-install-sozu.log](https://github.com/sozu-proxy/sozu/files/7739777/cargo-install-sozu.log)

And tailing two errors in text
```
error: cannot find macro `many0` in this scope
  --> /Users/avelier/.cargo/registry/src/github.com-1ecc6299db9ec823/sozu-lib-0.13.1/src/protocol/http/cookies.rs:42:49
   |
42 |   let res: IResult<&[u8], Vec<RequestCookie>> = many0!(input, complete!(single_request_cookie));
   |                                                 ^^^^^

error: cannot find macro `named` in this scope
  --> /Users/avelier/.cargo/registry/src/github.com-1ecc6299db9ec823/sozu-lib-0.13.1/src/protocol/http/cookies.rs:25:1
   |
25 | named!(pub single_request_cookie<RequestCookie>,
   | ^^^^^
```

system and rust versions:
```
      System Version: macOS 12.0.1 (21A559)
      Kernel Version: Darwin 21.1.0
```
```
➜ rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.58.0-beta.2 (0e07bcb68 2021-12-04)`
```

0.12.0 is fine for me for now. Thank you!

**Comment by quietlychris** [comment]
I am having the same issue with `0.13.1` attempted using `$ cargo install sozu` on Pop!_OS 21.04 (an Ubuntu-like system) using `rustc 1.59.0-nightly (23f69235a 2021-12-20)`.

**Comment by JonasWijne** [comment]
same here on arch linux `Kernel: 5.16.5-arch1-1` with `0.13.1` using  `rustc 1.58.1 (db9d1b20b 2022-01-20)`

**Comment by c-key** [comment]
I have the same issue on debian bullseye with 0.13.1 using rustup with rustc 1.58.1. Is there another way to install sozu?

**Comment by FlorentinDUBOIS** [comment]
This errors seems to be related to an old version of sozu. I have to update the version on crates.io which will fix the issue
