### ISSUE TITLE
Add custom tags to access-logs

### ISSUE THREAD

**Issue by PierreZ** [sozu-proxy/sozu#756]
Hey :wave: 

We would like to be able to add custom tags to a frontend(or backend) configuration. These tags could be logged within an access-log, allowing us to improve access-logs analytics with already-enriched events. These tags must be configured during the configuration of a frontend/backend.

**Comment by FlorentinDUBOIS** [comment]
Hey @PierreZ :wave:,

I dig into the source code of Sōzu 0.13.6 to find out how achieve this issue. 

Firstly, we will need to update the [`HttpAppConfig`](https://github.com/sozu-proxy/sozu/blob/5e7a49138fb23e4ae28e08193f223f90e2711bfa/command/src/config.rs#L512) structure and the according [`Application`](https://github.com/sozu-proxy/sozu/blob/32f02ac345a8e7491bcaa0f014ee8b2410573050/command/src/proxy.rs#L227) structure that is used to serialize orders to Sōzu. Once, this is done, Sōzu store those applications at the [`Proxy`](https://github.com/sozu-proxy/sozu/blob/292a1d5b4016c6bfc8f586d3d1aeea7225bd6e18/lib/src/http.rs#L806)-level, we will be able to retrieve them in the [`Server::run`](https://github.com/sozu-proxy/sozu/blob/dba3dd6d2e781e28528b4da6b9cc6e2d592faa86/lib/src/server.rs#L298) method and inject those information at some point to the [`Session`](https://github.com/sozu-proxy/sozu/blob/292a1d5b4016c6bfc8f586d3d1aeea7225bd6e18/lib/src/http.rs#L49) structure. Then, you will have to pass those metadata at the underlying structure [`Http<Front>`](https://github.com/sozu-proxy/sozu/blob/292a1d5b4016c6bfc8f586d3d1aeea7225bd6e18/lib/src/protocol/http/mod.rs#L67) which is responsible to create the access log using the [`info_access!`](https://github.com/sozu-proxy/sozu/blob/292a1d5b4016c6bfc8f586d3d1aeea7225bd6e18/lib/src/protocol/http/mod.rs#L529) macro.

Of course, this is for http, we have to do the same for tcp and https requests.

**Comment by Keksoj** [comment]
This is closed by: 

- #770

Thank you @FlorentinDUBOIS that was awesome.
