### ISSUE TITLE
Clarification of proxy working with frontend path

### ISSUE THREAD

**Issue by c-key** [sozu-proxy/sozu#761]
I have a question to clarify how sozu proxy work with paths and query parameters.
When I config a frontend with a host and a path, it will say sozu only proxy to backend when the host match and also the url path begins with the path from frontend config. But what parts will be transfered to the backend of the source request?
Query parameters?
original Url path or url path without the defined frontend path in the config?

Thanks.

**Comment by FlorentinDUBOIS** [comment]
Hey @c-key,

Firstly, thank you for your interest in Sōzu. I made some tests to ensure that I give you the right answer. So, if you configure Sōzu with something which seems pretty near to:

```toml
[applications.my-app]
frontends = [
  { address = "0.0.0.0:8080", hostname = "lolcatho.st", path_begin = "/api" },
]

backends = [
  { address = "127.0.0.1:3000" }
]
```

I send the following curl:

```shell
$ curl -s -vvvv http://lolcatho.st:8080/api/foo?query=1
*   Trying 127.0.0.1:8080...
* Connected to lolcatho.st (127.0.0.1) port 8080 (#0)
> GET /api/foo?query=1 HTTP/1.1
> Host: lolcatho.st:8080
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< accept-ranges: bytes
< Date: Fri, 25 Feb 2022 08:51:21 GMT
< Keep-Alive: timeout=5
< Content-Length: 0
< Sozu-Id: 01FWR17NVTDHQA3PJWF1YX916F
< 
* Connection #0 to host lolcatho.st left intact
```

From the point of view of Sōzu, we got:

```txt
2022-02-25T08:51:21.087823Z 1645779081087823091 433916 WRK-00 INFO      01FWR17NVTDHQA3PJWF1YX916F MyApp MyApp-0-127.0.0.1:3000 127.0.0.1:46500 -> 127.0.0.1:3000       5657μs 388μs 95 164 HTTP lolcatho.st:8080 GET /api/foo?query=1      404 Not Found
``` 

From the point of view of the back-end, we got:

```txt
[2022-02-25T08:51:21.084Z]  "GET /api/foo?query=1" "curl/7.81.0"
[2022-02-25T08:51:21.086Z]  "GET /api/foo?query=1" Error (404): "Not found"
```

So, to answer sure you properly when using the `path_begin` feature, Sōzu do not touch the path and query parameters, it forward them as-is.

I hope this help you :smile:

**Comment by c-key** [comment]
Thanks for your answer, now it is more clearly.
But is there a way to configure Sōzu to trim the path_begin before the path and query will be forwarded to the backend?

**Comment by FlorentinDUBOIS** [comment]
Currently, this feature does not exist. This is something that will be possible to do thank to wasm plugins. This work is identified and relate to https://github.com/sozu-proxy/sozu/labels/wasm issues. We would like to provide an experience similar to [redirection.io](https://redirection.io/).

**Comment by c-key** [comment]
OK, thanks for your answer and the information.
