### ISSUE TITLE
Declare sozu's interpretation of AGPL "covered work"

### ISSUE THREAD

**Issue by jtroo** [sozu-proxy/sozu#764]
Hello! I think it would be useful for potentials users to declare in the README how the sozu project interprets the AGPL's meaning of a "covered work". 

> A "covered work" means either the unmodified Program or a work based on the Program.

Unfortunately it is not explicit and is up to the courts to determine. I've read up of one instance of AGPL being tried in court in the past. Some AGPL library (something like a PDF parser, I don't remember) was being called into by a proprietary program, and since the court determined that since the AGPL library was providing important functionality for the proprietary program, the proprietary program was deemed a "covered work".

However, the sozu project's functionality is encountered quite early in an overall system and is very generic - it moves traffic around (I know, simplification, but bear with me). So does the sozu project consider a service that is the target of a reverse proxy to be a "covered work"?

For an example of a project that explicitly declares its interpretation of a covered work, see makeself:
https://github.com/megastep/makeself#license

**Comment by StevenLeRoux** [comment]
Readme updated. Thanks for asking for clarification @jtroo 

Closing this issue.
