### ISSUE TITLE
Zombie check crashes worker server

### ISSUE THREAD

**Issue by Wonshtrum** [sozu-proxy/sozu#808]
Sōzu zombie session check causes the whole worker to crash if it finds and tries to kill such a session:

    panicked at 'already borrowed: BorrowMutError', lib/src/http.rs:822:32

At first glance, it seems to me that this is due to `close_session` being called from a "borrowed mut" `SessionManager` and internally calling `close_backend` which tries to "borrow mut" *again* the `SessionManager`:
https://github.com/sozu-proxy/sozu/blob/e3e4e2374b9315c60674278015a992e4394103d3/lib/src/server.rs#L702
https://github.com/sozu-proxy/sozu/blob/e3e4e2374b9315c60674278015a992e4394103d3/lib/src/server.rs#L193-L196
https://github.com/sozu-proxy/sozu/blob/e3e4e2374b9315c60674278015a992e4394103d3/lib/src/http.rs#L1210-L1223
https://github.com/sozu-proxy/sozu/blob/e3e4e2374b9315c60674278015a992e4394103d3/lib/src/http.rs#L814-L822

**Comment by FlorentinDUBOIS** [comment]
This issue is closed thanks to the pr #812
