### ISSUE TITLE
Brotli pass-through

### ISSUE THREAD

**Issue by PlainBane** [sozu-proxy/sozu#822]
Hello,
Is there a reason for not including brotli pass-through in sozu? My static web-server supports brotli compression, but sozu breaks it. Client browser, just, gets gzip. So I did an experiment to see what happens if I add brotli to http response header.

_lib/src/protocol/http/parser/mod.rs_
`pub enum TransferEncodingValue {
    Chunked,
    Compress,
    Deflate,
    Gzip,
    Br,
    Identity,
    Unknown,
}`

Now firefox and chromium based browsers get brotli from my server through sozu.

**Comment by FlorentinDUBOIS** [comment]
Hey @PlainBane, 

We did not test brotli-compression, I will do some tests and if it works properly, I will release it. Thanks you for the issue and contribution

**Comment by Keksoj** [comment]
I did not manage to reproduce this issue. With this configuration:

- a GET request sent with [postman](https://www.postman.com/) with `Accept-Encoding` header set to `br` only (usually it's `gzip, deflate, br`)
- a web server build with [actix-web](https://docs.rs/actix-web/latest/actix_web/) and the [compress middleware](https://docs.rs/actix-web/latest/actix_web/middleware/struct.Compress.html#impl-Default-for-Compress) set to default values
- Sōzu in between, with standard values for listener, frontend and backend

I get a response with this header: `content-encoding: br`

That being said, adding `Br` to `TransferEncodingValue` is easy and doesn't alter sozu's behaviour much, so we could just as well add it, maybe I'm missing something.

**Comment by PlainBane** [comment]
I used Lighttpd static server. Did not test with actix-web or anything else. Could be that it depends on server. In Lighttp, I could not get 'br' to function without this.

**Comment by FlorentinDUBOIS** [comment]
As you said @Keksoj, we could easily add the `Br` enum variant. To me, we could add it to get more compatibility with other servers.

**Comment by Keksoj** [comment]
This is done in #845 ;-) After #845 is merged, it would be nice if you could retest Sōzu with this newest modification to check if Brotli is passed through the way you wanted it to be, @PlainBane
