### ISSUE TITLE
the request URL can contain the host and port

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#84]
In gitlab by @Geal on Nov 4, 2016, 10:26

apparently, when the URL and the Host header disagree, the URL is the right one, but should we really accept requests with this error?

**Comment by 46bit** [comment]
Could you assign this to me and I'll get it done in the next week or so?

**Comment by BlackYoup** [comment]
About how to handle the request error: from the [spec](https://tools.ietf.org/html/rfc7230#section-5.4) it seems like this header is used for routing requests. So I guess we should definitively answer a 404 (or 400?) if both values does not match.

For the record, haproxy answers a 404

**Comment by Geal** [comment]
I think a 400 would be better, but 404 can work

**Comment by Geal** [comment]
fixed in 22e8061. Right now if there's both an absolute URL in request line it's treated as invalid parsing, so no 404 error
