### ISSUE TITLE
HTTP 502 error with websocket pass-through

### ISSUE THREAD

**Issue by sebartyr** [sozu-proxy/sozu#885]
Using websocket pass-through on HTTP port causes an 502 error.

An example : https://github.com/Ten0/coinche-server-rs (Waiting for dependencies upgrade in this project)

**Comment by Wonshtrum** [comment]
The Actix server sends the following response to the WebSocket request:
```http
HTTP/1.1 101 Switching Protocols
transfer-encoding: chunked
connection: upgrade
upgrade: websocket
sec-websocket-accept: ujzrx+YctV9iV7wc7GJVQzqOLj8=
strict-transport-security: max-age=31536000; includeSubDomains; preload
date: Mon, 23 Jan 2023 16:27:37 GMT
```
The `transfer-encoding` is problematic and is rejected by Sozu, which terminates the backend connection and sends a 502 to the client.
The RFC7230 is clear on the subject:
https://greenbytes.de/tech/webdav/rfc7230.html#header.transfer-encoding

> A server MUST NOT send a Transfer-Encoding header field in any response with a status code of [1xx (Informational)](https://greenbytes.de/tech/webdav/rfc7231.html#status.1xx) or [204 (No Content)](https://greenbytes.de/tech/webdav/rfc7231.html#status.204). A server MUST NOT send a Transfer-Encoding header field in any [2xx (Successful)](https://greenbytes.de/tech/webdav/rfc7231.html#status.2xx) response to a CONNECT request ([Section 4.3.6](https://greenbytes.de/tech/webdav/rfc7231.html#CONNECT) of [[RFC7231]](https://greenbytes.de/tech/webdav/rfc7230.html#RFC7231)).

The upgrade header triggers this code path that only accept responses in the `HasStatusLine`:
https://github.com/sozu-proxy/sozu/blob/e1460746785a6f2f7ff6b9ca5a83d046b486384a/lib/src/protocol/http/parser/response.rs#L234-L240
Excluding, in particular, the `HasLength` state:
https://github.com/sozu-proxy/sozu/blob/e1460746785a6f2f7ff6b9ca5a83d046b486384a/lib/src/protocol/http/parser/response.rs#L15-L33

This is a generic problem that stems from the fact that browsers are lax with their parsing, especially with headers, often ignoring invalid ones. Some HTTP frameworks take advantage of this by crafting requests and responses that don't respect all the RFCs. This is the case with Actix setting a `transfer-encoding` on a 1xx response. Hyper had a similar problem, setting `content-length` on 1xx responses.

Do we want to "fix" this by making Sozu less strict?

**Comment by FlorentinDUBOIS** [comment]
Hey @sebartyr, it is nice to see you there! 

@Wonshtrum it is a really nice description of what happen. To me, I prefer to respect the RFC, but this is not the best way to treat this issue. In Sōzu, we already have a compiler feature flag that allow to switch at the compilation to a "tolerant http parser". 
This compiler feature flag is named [`tolerant-http1-parser`](https://github.com/sozu-proxy/sozu/blob/main/lib/Cargo.toml#L74) and it is enabled on Clever Cloud. 

So, what we could do here is to keep the actual implementation as it respects the [`RFC 7231`](https://greenbytes.de/tech/webdav/rfc7230.html#header.transfer-encoding) and add the lax behavior behind the compiler feature flag.

What do you think about this?

**Comment by FlorentinDUBOIS** [comment]
Thanks @Keksoj for the triage :)

**Comment by Geal** [comment]
The tolerant http parser feature was about accepting different charsets IIRC. Ideally sozu would be able to stay strict but there will always be some specific cases, and the issue with cargo features is that at some point there's a lot of code paths that are rarely exercized.
If more flags to tweak the state machine are added, then it would be worth the effort to handle those flags at runtime instead of in cargo features (and still try to keep them to a minimum, because the combinations will become unwieldy very soon)

**Comment by Keksoj** [comment]
I second the idea of bending the RFC in this place, when this feature flag is applied. That looks perfect to me.

**Comment by Ten0** [comment]
In case that can be useful, https://github.com/Ten0/coinche-server-rs/commit/f99c998ab8746235e248b999f5d4014527a40518 upgrades the example server from [the original post](https://github.com/sozu-proxy/sozu/issues/885#issue-1553377800) to a more recent actix version.

**Comment by Keksoj** [comment]
This behaviour should be handled in a end-to-end test, this is a job for @Wonshtrum

**Comment by Wonshtrum** [comment]
Parsers were relaxed with the introduction of kawa (in #904) and this particular case is included in our end to end tests:
https://github.com/sozu-proxy/sozu/blob/55580c6da130de15e05f19f72640c364f117bec9/e2e/src/tests/tests.rs#L813-L818
