### ISSUE TITLE
refactoring the HTTP header parser

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#92]
In gitlab by @Geal on Dec 5, 2016, 18:13

The approach using an enum worked quite well to separate the various steps in parsing headers, but now it needs to have states combining length, host, connection, upgrade protocol. Until the end of the headers is reached, the various values we need to gather should be in a structure with optional fields. This will reduce the number of states, and we can still check if something has been already parsed or not.

The new state machine would keep the various end states.

**Comment by Freyskeyd** [comment]
@Geal This refactoring is still needed?

Do you have some more details to provide?

**Comment by Geal** [comment]
in progress on the dev branch

**Comment by Keksoj** [comment]
All HTTP parsing is done with Kawa now, so this issue can't be relevant anymore.
