### ISSUE TITLE
useful statistics

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#96]
In gitlab by @Geal on Dec 12, 2016, 18:14

currently, the proxy does not measure timings or valid/invalid requests ratios. There was a small solution to send statistics to a graphite server via an UDP connection, but it is brittle.

ideas:
- accumulate statistics in each proxy, give them to the master when the master requests them. The master is then responsible for displaying the statistics or forwarding them to another service. This allows aggregation of data from multiple workers
- there are statistics to gather per connection: service time (time actually spent on that connection), latency front->back, latency back->front, number of bytes
- there are statistics per worker: number of failed connections in the last X minutes (or since the last statistics query?)
- make a command line dashboard with blessed? https://github.com/yaronn/blessed-contrib
- display statistics on a local HTTP server?

**Comment by Geal** [comment]
In gitlab by @Geal on Dec 12, 2016, 18:17

added ~206 label

**Comment by Geal** [comment]
In gitlab by @divarvel on Dec 22, 2016, 15:12

If polling makes sense, exposing JSON stats through a HTTP server or a file would be a good solution (and would give out-of-the box telegraf support).

**Comment by divarvel** [comment]
I think exposing metrics over HTTP on a domain socket would be the simplest solution.

**Comment by Geal** [comment]
with #213 and #172 done, the only thing missing here is actually measuring useful stuff, like #220.
For reference, here are some links about important haproxy metrics:
- https://www.datadoghq.com/blog/monitoring-haproxy-performance-metrics/
- https://gist.github.com/alq666/20a464665a1086de0c9ddf1754a9b7fb

**Comment by Geal** [comment]
see also #185

**Comment by Geal** [comment]
moving to "nice to have" milestone, since we already have a lot of useful things for the current release
