### ISSUE TITLE
Read the file of LoadState with streaming (instead of buffering)

### ISSUE THREAD

**Issue by Keksoj** [sozu-proxy/sozu#971]
We are limited by the max size of the buffer when reading a file to load state from.

Reading the file in streaming would solve this limit.

**Comment by Keksoj** [comment]
It seems the bug lies in the size of the buffer that is set to 200 KB when loading a state file:

https://github.com/sozu-proxy/sozu/blob/af46592669ba672baebaa5b55bbc6321c8d79047/bin/src/command/requests.rs#L192C42-L192C42

Here is the bug and how to reproduce it, with Sōzu version 0.15.2.

1. run Sōzu with the default config file. `sozu -c config.toml start`
2. send `AddCluster`, `AddListener`, `AddHttpFrontend` and `AddBackend` requests to alter the state of Sōzu with a lot of random clusters, using for instance this home-made [traffic-generator](https://github.com/Keksoj/sozu-traffic-generator)
3. save the state of Sōzu to a `state.json` file with `sozu -c config.toml state save --file state.json`
4. check that the size of the `state.json` **exceeds 200 KB**. If not, repeat 2 and 3.
5. stop Sōzu and restart it as in step 1
6. try to load the `state.json` file with `sozu -c config.toml state load --file state.json`

Loading the state fails with this error:

```
2023-07-28T11:04:59.493845Z 1690542299493845063 64353 MAIN ERROR	saved state parse error: Failure(ParseError { kind: MapRes, serde_json_error: Some(Error("EOF while parsing a string", line: 1, column: 237)) })
```

Since this issue does not arise whith a `state.json` **under 200 KB**, it seems the issue has its root in the size of the buffer.

**Comment by Geal** [comment]
What changed in load state recently? It used to be able to read very large files

**Comment by Keksoj** [comment]
What changed since 0.13.6 :
- a lot of refactoring around the `CommandServer` to make it event-based
- the error management around the methods of the `CommandServer`
- nothing to the buffer management (that I am aware of)
- the parse function, that we rewrote together:

In 0.13.6:
https://github.com/sozu-proxy/sozu/blob/e4e7488232ad6523791b94ad201239bcf7eb9b30/bin/src/command/orders.rs#L1236-L1246

in 0.15.2:
https://github.com/sozu-proxy/sozu/blob/af46592669ba672baebaa5b55bbc6321c8d79047/command/src/parser.rs#L45-L73

Would that explain anything?

**Comment by Geal** [comment]
not in the parse function itself but in the code that calls it and is supposed to refill the buffer when the parser returns Incomplete

**Comment by Keksoj** [comment]
I tried flipping the parsing function to its former version and it worked. We must have missed something back then. Will try to find out what.

Thanks a lot for your insights! Your questions were helpfull.

**Comment by FlorentinDUBOIS** [comment]
I close this pull request as we merge #972 and it works again on large file.
