### ISSUE TITLE
don't know how to use 

### ISSUE THREAD

**Issue by conanchen** [sozu-proxy/sozu#982]
newbie question: 

I run exampls/minimal.rs on vscode and tried to test it with http://127.0.0.1:8080/ on chrome, got message on terminal console:

```
    Finished dev [unoptimized + debuginfo] target(s) in 2.56s
     Running `target/debug/examples/minimal`
2023-08-21T10:04:45.976122Z 1692612285976122000 69589 EXAMPLE INFO      starting up
HTTP -> Ok(WorkerResponse { id: "add-the-cluster", status: Ok, message: "", content: None })
HTTP -> Ok(WorkerResponse { id: "add-the-cluster", status: Ok, message: "", content: None })
2023-08-21T10:05:07.945690Z 1692612307945690000 0 SOZU ERROR    
Error connecting to backend: failed to retrieve the cluster: 
failed to retrieve the frontend for the request: no cluster found
```

what I want to have with sozu to access the external webpages just like local server:

I want to access my url like http://localhost:8080/external?url=www.example.com and I can get www.example.com content.  

any suggestion? thanks.

**Comment by Wonshtrum** [comment]
Hello! Unfortunately, you can't do that with Sozu.
It sounds like you're looking for a solution that resembles a proxy more than a reverse proxy. To clarify, a reverse proxy often reroutes external traffic to internal servers based on frontends, while a proxy typically handles internal traffic and forwards it externally, like to the Internet. Given your goal of accessing external content via a URL parameter, a regular proxy is likely a better fit.

If you want a quick and dirty solution, you can run a local web server that does the redirection. Here is a Python script that may help you:
```py
from flask import Flask, request, Response
import requests

app = Flask(__name__)

@app.route('/external', methods=['GET'])
def external():
    url = request.args['url']
    resp = requests.get(f'https://{url}')
    return resp.content, resp.status_code
```
