### ISSUE TITLE
Invalid links in `how_to_use.md` documentation 

### ISSUE THREAD

**Issue by nikhilraojl** [sozu-proxy/sozu#983]
From https://github.com/sozu-proxy/sozu/blob/main/doc/how_to_use.md#systemd-integration

> The repository provides a unit file [here](https://github.com/sozu-proxy/sozu/blob/main/os-build/systemd/sozu.service.in). You can copy it to /etc/systemd/system/ and invoke systemctl daemon-reload.

the above link to unit file returns 404. The file `os-build/systemd/sozu.service.in` was renamed in #945 

> You can use a bash script and call sed to automate this part. e.g.: [generate.sh](https://github.com/sozu-proxy/sozu/blob/main/os-build/exherbo/generate.sh).

`generate.sh` example link also returns 404. There is no exherbo directory present in os-build

**Comment by Keksoj** [comment]
you're right!

**Comment by Keksoj** [comment]
fixed by #984
