### ISSUE TITLE
Unable to install on Aarch64

### ISSUE THREAD

**Issue by newdev8** [sozu-proxy/sozu#989]
I was trying to install `sozu` on a Orange Pi 5 but I was getting error `could not find 'x86_64' in 'arch'` from `kawa`.
There is a [merged pull request](https://github.com/CleverCloud/kawa/pull/6) that fixes this issue but has not been yet updated on [crates.io](https://crates.io).

I had to change the `kawa` dependency manually to point to the [git repo](https://github.com/CleverCloud/kawa) and add `features = []`, then everything worked fine.

**Comment by Keksoj** [comment]
Kawa has been released with 0.6.3, and Sōzu does use this new version too. Does the problem still arise ?

**Comment by newdev8** [comment]
Hello, sorry for the late response.
No, it hasn't been fixed yet, I'm still getting the exact same error.

Now I didn't have to point to the git repo but I did have to change the features.
The problem has to do with the feature `simd` which is not compatible with `aarch64`.
To fix it I had to modify [`lib/Cargo.toml`](https://github.com/sozu-proxy/sozu/blob/main/lib/Cargo.toml) and remove the line `simd = ["kawa/simd"]` under `[features]`.

**Comment by Wonshtrum** [comment]
Sorry, I didn't see your answer. Yes as of today the building process is a bit cumbersome. You can achieve the same result by building sozu without default features as documented in the lib [README](https://github.com/sozu-proxy/sozu/tree/main/lib#build-with-or-without-simd). In the future, I hope the switch will be based on the targeted architecture so the user doesn't have to fiddle with the features. For now, we are primarily focused on more urgent development tasks.

**Comment by Keksoj** [comment]
Kawa has been updated since, the problem should not arise anymore.
